Repository tardis-sn/tardis, pull requests merged in 2020-06, with the labels that each got.

#1158 Make consistency edits to documentation
  docs/atomic/atomic_data_description.rst
  docs/configuration/config_validator.rst
  docs/configuration/configuration.rst
  docs/configuration/read_configuration.ipynb
  docs/credits.rst
  docs/development/continuous_integration.rst
  docs/development/developer_faq.rst
  docs/development/git_workflow.rst
  docs/development/index.rst
  docs/development/issues.rst
  docs/development/release_workflow.rst
  docs/development/running_tests.rst
  docs/development/update_refdata.rst
  docs/index.rst
  docs/installation.rst
  docs/models/examples/Custom_Density_And_Boundary_Velocities.ipynb
  docs/models/examples/abundancecust.rst
  docs/models/examples/abundanceuni.rst
  docs/models/examples/densitycust.rst
  docs/models/examples/densityexp.rst
  docs/models/examples/densitypow.rst
  docs/models/examples/modelconfig.rst
  docs/models/index.rst
  docs/physics/index.rst
  docs/physics/montecarlo/discretization.rst
  docs/physics/montecarlo/estimators.rst
  docs/physics/montecarlo/index.rst
  docs/physics/montecarlo/lineinteraction.rst
  docs/physics/montecarlo/propagation.rst
  docs/physics/montecarlo/randomsampling.rst
  docs/physics/montecarlo/sourceintegration.rst
  docs/physics/montecarlo/virtualpackets.rst
  docs/physics/montecarlo_old.rst
  docs/physics/new_plasma.rst
  docs/physics/physical_quantities.ipynb
  docs/physics/plasma/helium_nlte.rst
  docs/physics/plasma/lte_plasma.rst
  docs/physics/plasma/macroatom.rst
  docs/physics/plasma/nebular_plasma.rst
  docs/physics/plasma/nlte.rst
  docs/quickstart/quickstart.ipynb
  docs/research/code_comparison/index.rst
  docs/running/commandline.rst
  docs/running/converters/cmfgen.rst
  docs/running/gui.rst
  docs/running/interaction/index.rst
  docs/running/interaction/integrator.ipynb
  docs/team.rst
Labels: documentation

#1193 Unpin astropy version
  tardis_env3.yml
Labels: conda

#1195 Fix badges in README.rst
  README.rst
Labels: documentation

#1197 add arjun's name to the ORCID list
  .orcid.csv
Labels: documentation

#1203 Minor changes to the environment file and cleanup
  .readthedocs.yml
  azure-pipelines/simple_test_framework.yml
  readthedocs.yml
  tardis_env3.yml
Labels: pipelines
