Repository tardis-sn/tardis, pull requests merged in 2020-11, with the labels that each got.

#1332 Remove helper scripts
  azure-pipelines/doc-build.yml
  ci-helpers/fetch_reference_data.sh
  ci-helpers/install_miniconda.sh
  ci-helpers/install_tardis_env.sh
  deploy_docs.sh
  tardis/scripts/update_changelog.sh
Labels: codestyle

#1330 Small fix for release pipeline
  azure-pipelines/templates/default.yml
  docs/development/azure_links.inc
  docs/development/continuous_integration.rst
Labels: CI-CD

#1300 Remove pip install option from TARDIS installation docs
  docs/installation.rst
Labels: documentation

#1333 Rename testing pipeline
  azure-pipelines/run-unit-tests.yml
Labels: CI-CD

#1352 Add Arjun's emails to .mailmap
  .mailmap
Labels: documentation, easy

#1359 Fix of Issue #680
  ah_bootstrap.py
  docs/physics/plasma/plasma_plots/lte_ionization_balance.py
  docs/physics/plasma/plasma_plots/nebular_ionization_balance.py
  tardis/_astropy_init.py
  tardis/base.py
  tardis/gui/datahandler.py
  tardis/gui/interface.py
  tardis/gui/widgets.py
  tardis/io/atom_data/atom_web_download.py
  tardis/io/atom_data/base.py
  tardis/io/atom_data/util.py
  tardis/io/config_reader.py
  tardis/io/config_validator.py
  tardis/io/decay.py
  tardis/io/model_reader.py
  tardis/io/parsers/blondin_toymodel.py
  tardis/io/parsers/csvy.py
  tardis/io/util.py
  tardis/model/base.py
  tardis/model/density.py
  tardis/montecarlo/base.py
  tardis/montecarlo/packet_source.py
  tardis/plasma/base.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/continuum_processes.py
  tardis/plasma/properties/ion_population.py
  tardis/plasma/properties/level_population.py
  tardis/plasma/properties/partition_function.py
  tardis/plasma/properties/plasma_input.py
  tardis/plasma/properties/radiative_properties.py
  tardis/plasma/standard_plasmas.py
  tardis/simulation/base.py
  tardis/stats/base.py
  tardis/tests/integration_tests/plot_helpers.py
  tardis/util/base.py
  tardis/widgets/plot_util.py
  tardis/widgets/util.py
Labels: documentation
