Repository tardis-sn/tardis, pull requests merged in 2020-07, with the labels that each got.

#1136 Debugging relativity on numba_montecarlo
  docs/development/debug_numba.rst
  docs/development/index.rst
  tardis/io/schemas/montecarlo.yml
  tardis/montecarlo/__init__.py
  tardis/montecarlo/base.py
  tardis/montecarlo/formal_integral.py
  tardis/montecarlo/montecarlo.pyx
  tardis/montecarlo/montecarlo_configuration.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/montecarlo_logger.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/montecarlo/setup_package.py
  tardis/montecarlo/src/abbrev.h
  tardis/montecarlo/src/cmontecarlo.c
  tardis/montecarlo/src/cmontecarlo.h
  tardis/montecarlo/src/integrator.c
  tardis/montecarlo/src/integrator.h
  tardis/montecarlo/src/io.h
  tardis/montecarlo/src/omp_helper.h
  tardis/montecarlo/src/randomkit/LICENSE
  tardis/montecarlo/src/randomkit/randomkit.h
  tardis/montecarlo/src/randomkit/rk_isaac.c
  tardis/montecarlo/src/randomkit/rk_isaac.h
  tardis/montecarlo/src/randomkit/rk_mt.c
  tardis/montecarlo/src/randomkit/rk_mt.h
  tardis/montecarlo/src/randomkit/rk_primitive.c
  tardis/montecarlo/src/randomkit/rk_primitive.h
  tardis/montecarlo/src/randomkit/rk_sobol.c
  tardis/montecarlo/src/randomkit/rk_sobol.h
  tardis/montecarlo/src/rpacket.c
  tardis/montecarlo/src/rpacket.h
  tardis/montecarlo/src/status.h
  tardis/montecarlo/src/storage.h
  tardis/montecarlo/tests/conftest.py
  tardis/montecarlo/tests/test_formal_integral.py
  tardis/montecarlo/tests/test_montecarlo.py
  tardis/scripts/debug/run_numba_single.py
  tardis/scripts/debug/run_numba_single.run.xml
  tardis/scripts/debug/tardis_example_single.yml
  tardis/simulation/base.py
  tardis/tests/test_tardis_full.py
  tardis/tests/test_tardis_full_formal_integral.py
  tardis_env3.yml
Labels: montecarlo, relativity

#1219 Update index.rst to add mission statement
  docs/index.rst
Labels: documentation

#1190 Change `pytestconfig` to `request.config`
  tardis/conftest.py
  tardis/montecarlo/tests/test_packet_source.py
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/tests/integration_tests/test_integration.py
Labels: testing

#1218 Move and rename coverage file
  .coveragerc
Labels: testing

#1227 Restore caching to spectrum_integrated
  tardis/montecarlo/base.py
Labels: formal integral
