Repository tardis-sn/tardis, pull requests merged in 2020-12, with the labels that each got.

#1331 Update changelog workflow
  .github/workflows/documentation-build.yml
  .github/workflows/update-changelog.yml
Labels: CI-CD

#1365 Parallel numba setup
  tardis/io/schemas/montecarlo.yml
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/__init__.py
Labels: numba, speedup

#1368 Fix of Issue #1176
  docs/atomic/atomic_data_description.rst
  tardis/gui/datahandler.py
Labels: documentation

#1354 Virtual packet logging fix
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/tests/test_numba_interface.py
Labels: bugfix, numba, virtual packets

#1375 Fixed real packet logging of properties
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/widgets/tests/test_line_info.py
Labels: bugfix, numba, priority - high

#1371 Reorganizing files in docs (1/2)
  CONTRIBUTING.md
  docs/governance.rst
  docs/physics/index.rst
  docs/physics/old_physics.rst
  docs/physics/plasma.rst
  docs/physics/plasma/old_plasma.rst
  docs/running/index.rst
  docs/running/interaction/Custom_TARDIS_Model_Tutorial.ipynb
  docs/running/interaction/commandline.rst
  docs/running/interaction/converters/cmfgen.rst
  docs/running/interaction/converters/index.rst
  docs/running/interaction/converters/mesa.stella.dat
  docs/running/interaction/converters/stella_to_tardis.ipynb
  docs/running/interaction/custom_source.ipynb
  docs/running/interaction/index.rst
  docs/running/interaction/integrator.ipynb
  docs/running/interaction/isotope_pd_subclass.ipynb
  docs/running/interaction/old_gui.rst
  docs/running/interaction/physical_quantities.ipynb
  docs/running/interaction/to_hdf.rst
  docs/running/interaction/using_formal_integral.rst
  docs/team.rst
Labels: documentation

#1378 Adding Plasma File in TOC
  docs/index.rst
Labels: documentation, priority - high

#1384 Small fixes for existing workflows
  .github/workflows/documentation-build.yml
  .github/workflows/update-changelog.yml
Labels: CI-CD

#1380 Packet logging fixes for visualization
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
Labels: Work in progress, bugfix, numba

#1387 Fixing docs building problem
  docs/quickstart/quickstart.ipynb
  docs/using/components/configuration/schemas/base.yml
  docs/using/components/configuration/schemas/model.yml
  docs/using/components/configuration/schemas/montecarlo.yml
  docs/using/components/configuration/schemas/plasma.yml
  docs/using/components/configuration/schemas/spectrum.yml
  docs/using/components/configuration/schemas/supernova.yml
  docs/using/components/models/examples/abund.dat
  docs/using/components/models/examples/density.dat
  docs/using/interaction/custom_source.ipynb
  docs/using/interaction/physical_quantities.ipynb
  docs/using/tardis_example.yml
Labels: documentation, priority - high

#1383 add preview docs section
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/documentation-build.yml
  docs/development/documentation_preview.rst
  docs/development/index.rst
Labels: documentation

#1369 Fix incorrect docstrings
  docs/conf.py
  docs/index.rst
  tardis/gui/datahandler.py
  tardis/io/decay.py
  tardis/io/util.py
  tardis/model/base.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/macro_atom.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/ion_population.py
  tardis/util/base.py
Labels: bugfix, documentation

#1395 Update Matterbridge docs
  docs/development/matterbridge.inc
  docs/development/matterbridge.rst
Labels: documentation

#1241 Add modified Kromer plot to work with widgets
  tardis/model/base.py
  tardis/montecarlo/base.py
  tardis/montecarlo/spectrum.py
  tardis/montecarlo/tests/test_spectrum.py
  tardis/widgets/__init__.py
  tardis/widgets/kromer_plot.py
Labels: gui

#1402 explicitly add parso to dependencies
  tardis_env3.yml
Labels: documentation, priority - high :fire:
