Repository tardis-sn/tardis, pull requests merged in 2020-09, with the labels that each got.

#1264 Add line info widget to widgets subpackage
  tardis/analysis.py
  tardis/widgets/__init__.py
  tardis/widgets/line_info.py
  tardis/widgets/shell_info.py
  tardis/widgets/tests/test_line_info.py
  tardis/widgets/tests/test_shell_info.py
  tardis/widgets/util.py
  tardis_env3.yml
Labels: gui

#1304 Use tardis-refdata from Azure mirror (CI/CD)
  azure-pipelines/simple_test_framework.yml
  azure-pipelines/templates/default.yml
  docs/development/azure_links.inc
  docs/development/continuous_integration.rst
  docs/development/git_links.inc
  docs/development/images/lock.png
  docs/development/images/secure_file.png
  docs/development/images/variables.png
  tardis/data/atomic_data_repo.yml
Labels: bugfix, documentation

#1299 Model configuration output in HDF
  tardis/io/config_reader.py
  tardis/io/tests/test_config_reader.py
Labels: configuration, needs review

#1274 Add space to plasma error message
  tardis/plasma/standard_plasmas.py
Labels: bugfix, plasma
