Repository tardis-sn/tardis, pull requests merged in 2021-03, with the labels that each got.

#1459 Removed the deprecated --with-vpacket-logging flag
  setup.py
  tardis/io/util.py
  tardis/montecarlo/base.py
  tardis/montecarlo/setup_package.py
Labels: priority - medium, virtual packets

#1470 Incorporating old physics section of the documentation
  docs/index.rst
  docs/physics/montecarlo/propagation.rst
  docs/physics/old_physics/index.rst
  docs/physics/old_physics/montecarlo_old.rst
  docs/physics/old_physics/old_plasma.rst
  docs/physics/plasma/index.rst
Labels: documentation

#1439 final changes for update refdata pipeline
  azure-pipelines/compare-refdata.yml
  azure-pipelines/run-unit-tests.yml
  azure-pipelines/update-refdata.yml
Labels: CI-CD

#1145 Add photoionization-related rates
  tardis/io/atom_data/base.py
  tardis/io/schemas/plasma.yml
  tardis/plasma/base.py
  tardis/plasma/properties/__init__.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/base.py
  tardis/plasma/properties/continuum_processes.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/properties/radiative_properties.py
  tardis/plasma/properties/transition_probabilities.py
  tardis/plasma/properties/util/macro_atom.py
  tardis/plasma/standard_plasmas.py
Labels: nebular

#1481 Added Documentation for Parallel execution with Numba and OpenMP
  docs/index.rst
  docs/installation.rst
  docs/using/interaction/using_formal_integral.rst
  docs/using/parallelisation/index.rst
Labels: GSoC, documentation

#1505 Fixing Visualization Notebook Hyperlink
  docs/using/visualization/generating_widgets.ipynb
Labels: documentation

#1492 Fix docstring mistakes in #1145
  tardis/io/atom_data/base.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/continuum_processes.py
  tardis/plasma/properties/transition_probabilities.py
Labels: documentation

#1502 Correct .coveragerc file
  .coveragerc
Labels: bugfix

#1498 Feature request: add virtual-packet-logging option to run_tardis()
  tardis/base.py
  tardis/montecarlo/base.py
  tardis/simulation/base.py
Labels: virtual packets

#1474 Docs Update
  docs/using/components/models/abundancecust/abundancecust.rst
Labels: documentation

#1477 Added option for keyword arguments in the TardisSpectrum's plot method
  tardis/montecarlo/spectrum.py
Labels: visualization

#1509 Collisional ionization
  tardis/plasma/properties/continuum_processes.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/properties/transition_probabilities.py
Labels: nebular, new feature 🚧, plasma

#1506 Add ability to plot only top contributing elements to SDEC plot
  tardis/visualization/tools/sdec_plot.py
Labels: visualization
