Repository tardis-sn/tardis, pull requests merged in 2021-09, with the labels that each got.

#1769 Changed the way `specific_log_level` flag works in the Logging Configuration
  tardis/io/logger/logger.py
Labels: bugfix, priority - high :fire:, logging

#1790 disable changelog in release pipeline
  .azure-pipelines/release-version.yml
Labels: CI-CD

#1784 Restructure Custom Abundance Widget code
  tardis/visualization/widgets/custom_abundance.py
Labels: visualization, restructure

#1757 Auto-Generating Tutorials Page
  docs/conf.py
  docs/index.rst
Labels: documentation
