Repository tardis-sn/tardis, pull requests merged in 2021-05, with the labels that each got.

#1554 Adding Config Value Validation for Different Parameters via Config File
  tardis/io/config_reader.py
  tardis/io/schemas/csvy_model.yml
  tardis/io/schemas/model.yml
  tardis/io/schemas/montecarlo.yml
  tardis/io/tests/test_config_reader.py
Labels: configuration

#1434 create update refdata pipeline
  azure-pipelines/compare-refdata.yml
  azure-pipelines/run-unit-tests.yml
  azure-pipelines/update-refdata.yml
Labels: CI-CD

#1528 Revising "Packet Propagation" page of physics docs
  docs/physics/montecarlo/discretization.rst
  docs/physics/montecarlo/images/expansion_animation.gif
  docs/physics/montecarlo/lineinteraction.rst
  docs/physics/montecarlo/propagation.rst
  docs/physics/montecarlo/randomsampling.rst
Labels: documentation

#1551 Adding Instructions For Enabling `virtual_packet_logging` Properties in Config
  docs/using/visualization/generating_widgets.ipynb
Labels: documentation

#1553 Fixing RST Formatting for `config_validator.rst`
  docs/using/components/configuration/config_validator.rst
Labels: documentation

#1559 Added support for passing Configuration object in run_tardis
  tardis/base.py
  tardis/tests/test_tardis_full.py
Labels: configuration

#1575 Fixing virtual_packet_logging instructions for line info widget
  docs/using/visualization/generating_widgets.ipynb
Labels: documentation

#1557 Changed Quickstart Example according to #1477
  docs/quickstart/quickstart.ipynb
Labels: documentation, priority - low

#1578 minor changes to compare refdata pipeline
  azure-pipelines/compare-refdata.yml
  tardis/__init__.py
Labels: CI-CD, bugfix

#1571 Fix numba deprecation
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis_env3.yml
Labels: numba

#1582 Fixing `Team` Link redirection in Code Of Conduct
  CODE_OF_CONDUCT.md
Labels: bugfix, documentation

#1581 changes to badges
  .github/workflows/documentation-build.yml
  README.rst
Labels: documentation, visualization

#1577 Fixing issues with `Citations` & `Label` references in Docs
  docs/development/continuous_integration.rst
  docs/development/documentation_guidelines.rst
  docs/development/git_workflow.rst
  docs/development/running_tests.rst
  docs/physics/montecarlo/propagation.rst
  docs/physics/plasma/macroatom.rst
  docs/physics/plasma/nebular_plasma.rst
  docs/tardis.bib
Labels: bugfix, documentation

#1584 Making sponsors page of documentation
  docs/graphics/esa.png
  docs/graphics/google.png
  docs/graphics/numfocus.png
  docs/index.rst
  docs/sponsors.rst
Labels: documentation

#1567 review environment file
  docs/conf.py
  tardis_env3.yml
Labels: install, priority - high :fire:

#1570 add fetch depth param to Azure template
  azure-pipelines/run-unit-tests.yml
  azure-pipelines/templates/default.yml
  docs/development/continuous_integration.rst
Labels: CI-CD

#1590 Fixing inconsistencies for `rst` formatting in Docs (Second Iteration)
  docs/development/update_refdata.rst
  docs/using/components/configuration/config_validator.rst
  docs/using/parallelisation/index.rst
  docs/zreferences.rst
  tardis/io/atom_data/base.py
Labels: documentation

#1596 Fixing bibliography in documentation build
  docs/zreferences.rst
Labels: bugfix, documentation
