Repository tardis-sn/tardis, pull requests merged in 2021-04, with the labels that each got.

#1479 getting rid of lexsort warning
  tardis/io/atom_data/base.py
Labels: bugfix

#1483 Corrected csvy model files
  docs/using/components/models/csvy_full_rad.csvy
  tardis/io/tests/data/csvy_full.csvy
Labels: bugfix, configuration, model

#1517 Add catch for missing elements in SDEC plot
  tardis/visualization/tools/sdec_plot.py
Labels: visualization

#1527 Fixing the documentation bug
  tardis_env3.yml
Labels: bugfix, documentation

#1478 add the symlink to visualization examples
  docs/using/visualization/tardis_example.yml
Labels: Work in progress, documentation

#1530 Small fixes in git_workflow guide
  docs/development/git_workflow.rst
Labels: documentation

#1499 [WIP] Enable full tests for Formal Integral
  tardis/tests/test_tardis_full_formal_integral.py
Labels: Work in progress, testing

#1512 Improved default number of interpolate_shells for the formal integral
  tardis/io/schemas/spectrum.yml
  tardis/montecarlo/formal_integral.py
Labels: formal integral

#1538 clean template files
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI-CD, codestyle

#1493 Added workflow for Documentation preview generation
  .github/workflows/documentation-preview.yml
  docs/development/continuous_integration.rst
  docs/development/documentation_preview.rst
Labels: CI-CD, documentation

#1450 string formatting done (try fixing all syntax errors)
  docs/conf.py
  tardis/analysis.py
  tardis/gui/widgets.py
  tardis/io/atom_data/atom_web_download.py
  tardis/io/atom_data/base.py
  tardis/io/atom_data/util.py
  tardis/io/config_internal.py
  tardis/io/config_validator.py
  tardis/io/decay.py
  tardis/io/model_reader.py
  tardis/io/parsers/blondin_toymodel.py
  tardis/model/density.py
  tardis/montecarlo/spectrum.py
  tardis/plasma/base.py
  tardis/plasma/exceptions.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/base.py
  tardis/plasma/properties/ion_population.py
  tardis/plasma/properties/nlte.py
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/simulation/base.py
  tardis/tests/fixtures/atom_data.py
  tardis/tests/integration_tests/conftest.py
  tardis/tests/integration_tests/plot_helpers.py
  tardis/tests/integration_tests/report.py
  tardis/tests/integration_tests/runner.py
  tardis/tests/integration_tests/test_integration.py
  tardis/tests/test_tardis_full.py
  tardis/tests/test_tardis_full_formal_integral.py
  tardis/util/base.py
  tardis/visualization/widgets/shell_info.py
Labels: Work in progress

#1539 Add ion contributions to SDEC plotter
  tardis/visualization/tools/sdec_plot.py
Labels: visualization

#1543 Restructuring r_packet.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/calculate_distances.py
  tardis/montecarlo/montecarlo_numba/estimators.py
  tardis/montecarlo/montecarlo_numba/frame_transformations.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/opacities.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
  tardis/montecarlo/montecarlo_numba/tests/test_vpacket.py
  tardis/montecarlo/montecarlo_numba/utils.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/montecarlo/tests/test_montecarlo.py
Labels: Work in progress, montecarlo, restructure
