Repository tardis-sn/tardis, pull requests merged in 2021-06, with the labels that each got.

#1592 Flexible packet initial radius
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/tests/conftest.py
  tardis/montecarlo/montecarlo_numba/tests/test_base.py
  tardis/montecarlo/packet_source.py
Labels: montecarlo

#1588 Added PR review checklist workflow
  .github/workflows/PR_review_checklist.yml
Labels: codestyle, documentation

#1602 add fetch depth param to changelog workflow
  .github/workflows/update-changelog.yml
Labels: CI-CD

#1601 Fixing documentation build
  docs/using/interaction/custom_source.ipynb
Labels: documentation

#1594 Fixing JSON Schema not Rendering Properly in the Documentation
  docs/using/components/configuration/configuration.rst
  tardis/io/schemas/model.yml
  tardis/io/schemas/model_definitions.yml
  tardis/io/schemas/montecarlo.yml
  tardis/io/schemas/montecarlo_definitions.yml
Labels: documentation

#1610 add token at checkout step
  .github/workflows/update-changelog.yml
Labels: CI-CD

#1555 Replacing the contents of the news section with TARDIS twitter feed
  docs/index.rst
  docs/news.rst
Labels: documentation

#1631 update mailmap and orcid
  .mailmap
  .orcid.csv
Labels: documentation, priority - high :fire:

#1622 Adding GitHub to sponsors page
  docs/graphics/github.png
  docs/sponsors.rst
Labels: documentation

#1623 force pyne nomoab_openmc version
  tardis_env3.yml
Labels: install, priority - high :fire:

#1595 move zenodo pipeline to GA
  .github/workflows/update-zenodo-json.yml
  azure-pipelines/update-zenodo-json.yml
  docs/conf.py
  docs/credits.rst
Labels: CI-CD

#1565 Fix for close line test.
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/calculate_distances.py
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/numba_config.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/tests/conftest.py
  tardis/montecarlo/montecarlo_numba/tests/test_base.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
  tardis/montecarlo/montecarlo_numba/tests/test_vpacket.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
Labels: bugfix, montecarlo

#1609 update refdata procedure docs
  docs/development/update_refdata.rst
Labels: documentation

#1648 fix compareWith parameter in release pipeline
  azure-pipelines/release-version.yml
Labels: CI-CD, priority - high :fire:

#1586 add gh pages instruction
  .github/workflows/documentation-preview.yml
  docs/development/documentation_preview.rst
Labels: documentation

#1645 configure codecov
  .codecov.yml
  .coveragerc
Labels: CI-CD

#1647 Fix for the v-packet logging while parallelism is enabled.
  tardis/montecarlo/montecarlo_numba/base.py
Labels: bugfix, numba

#1615 add flag to disable nbsphinx
  docs/conf.py
  docs/development/documentation_guidelines.rst
  docs/development/index.rst
  docs/io/optional/custom_source.ipynb
  docs/io/output/physical_quantities.ipynb
  docs/quickstart/quickstart.ipynb
Labels: documentation

#1650 Adding functionality to Detect Running Environments for TARDIS Simulations
  tardis/util/base.py
Labels: configuration, feature request, io

#1632 Formatting Logging Output for Simulation
  tardis/io/atom_data/base.py
  tardis/io/atom_data/util.py
  tardis/plasma/standard_plasmas.py
  tardis/simulation/base.py
  tardis/simulation/tests/test_simulation.py
  tardis/util/base.py
Labels: Work in progress

#1627 Correct misspelling in sdec_plot
  tardis/visualization/tools/sdec_plot.py
Labels: priority - low, visualization

#1589 Adding Interactive Initialization Documentation
  docs/io/optional/custom_source.ipynb
  docs/physics/montecarlo/basicprinciples.rst
  docs/physics/montecarlo/discretization.rst
  docs/physics/montecarlo/index.rst
  docs/physics/montecarlo/initialization.ipynb
  docs/physics/montecarlo/lineinteraction.rst
  docs/physics/montecarlo/propagation.rst
Labels: documentation

#1644 add mailmap check workflow
  .github/workflows/mailmap-check.yml
  .mailmap
Labels: CI-CD

#1657 Add SnakeViz profiling example
  docs/io/output/index.rst
  docs/io/output/profiling_example.ipynb
  docs/io/output/tardis_prof.png
  tardis_env3.yml
Labels: documentation

#1641 Editing Installation Page
  docs/installation.rst
Labels: documentation

#1630 Fix FileExistsError in to_hdf()
  tardis/io/util.py
Labels: bugfix

#1656 Editing sponsors and credits pages of documentation
  docs/credits.rst
  docs/sponsors.rst
Labels: documentation

#1659 Restructure Documentation pt. 2
  docs/physics/est_and_conv/convergence.rst
  docs/physics/est_and_conv/index.rst
  docs/physics/images/expansion_animation.gif
  docs/physics/images/optical_depth_summation.png
  docs/physics/images/scatter_downbranch_ma.png
  docs/physics/images/spherical_symmetry.png
  docs/physics/montecarlo/basicprinciples.rst
  docs/physics/montecarlo/index.rst
  docs/physics/montecarlo/initialization.ipynb
  docs/physics/montecarlo/lineinteraction.rst
  docs/physics/montecarlo/propagation.rst
  docs/physics/montecarlo/randomsampling.rst
  docs/physics/pyplot/lte_ionization_balance.py
  docs/physics/pyplot/nebular_ionization_balance.py
  docs/physics/setup/index.rst
  docs/physics/setup/model.rst
  docs/physics/setup/plasma/lte_plasma.rst
  docs/physics/setup/plasma/nebular_plasma.rst
  docs/physics/spectrum/basic.rst
  docs/physics/spectrum/index.rst
  docs/quickstart/quickstart.ipynb
Labels: documentation

#1667 Moving Profiling Page
  docs/development/images/tardis_prof.png
  docs/development/index.rst
  docs/development/profiling_example.ipynb
  docs/development/tardis_example.yml
  docs/io/output/index.rst
Labels: documentation

#1580 Port tardis_opacities script from tardisanalysis
  tardis/analysis/opacities.py
Labels: new feature 🚧, visualization

#1642 Adding Glossary
  docs/development/continuous_integration.rst
  docs/development/matterbridge.rst
  docs/physics/montecarlo/lineinteraction.rst
  docs/zreferences.rst
Labels: documentation
