Repository tardis-sn/tardis, pull requests merged in 2021-07, with the labels that each got.

#1633 Implementing Logging Configuration for Notebook Logging
  docs/io/optional/index.rst
  docs/io/optional/logging_configuration.ipynb
  docs/io/optional/tardis_config_logger.yml
  docs/quickstart/quickstart.ipynb
  tardis/__init__.py
  tardis/base.py
  tardis/io/schemas/base.yml
  tardis/io/schemas/debug.yml
  tardis/io/tests/data/tardis_configv1_verysimple_logger.yml
  tardis/simulation/base.py
  tardis/simulation/tests/test_simulation.py
Labels: Work in progress, feature request, new feature 🚧

#1679 Formatted files with Black
  tardis/io/tests/data/conf_def.yml
  tardis/io/tests/data/paper1_tardis_configv1.yml
  tardis/io/tests/data/tardis_configv1_artis_density.yml
  tardis/io/tests/data/tardis_configv1_artis_density_v_slice.yml
  tardis/io/tests/data/tardis_configv1_ascii_density.yml
  tardis/io/tests/data/tardis_configv1_ascii_density_abund.yml
  tardis/io/tests/data/tardis_configv1_ascii_density_uniabund.yml
  tardis/io/tests/data/tardis_configv1_density_exponential_test.yml
  tardis/io/tests/data/tardis_configv1_density_power_law_test.yml
  tardis/io/tests/data/tardis_configv1_isotope_uniabund.yml
  tardis/io/tests/data/tardis_configv1_tardis_model_format.yml
  tardis/io/tests/data/tardis_configv1_uniform_density.yml
  tardis/io/tests/data/tardis_configv1_verysimple.yml
  tardis/io/tests/data/tardis_configv1_verysimple_logger.yml
  tardis/model/base.py
  tardis/model/density.py
  tardis/model/tests/test_base.py
  tardis/model/tests/test_csvy_model.py
  tardis/model/tests/test_density.py
  tardis/montecarlo/montecarlo_numba/__init__.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/calculate_distances.py
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/frame_transformations.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/macro_atom.py
  tardis/montecarlo/montecarlo_numba/opacities.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/utils.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/montecarlo/setup_package.py
  tardis/montecarlo/spectrum.py
Labels: codestyle

#1678 Enabling Repository on Binder
  binder/environment.yml
  binder/postBuild
Labels: documentation

#1681 add latest black commit to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: codestyle

#1660 Small fixes to I/O documentation
  docs/io/configuration/components/atomic/atomic_data.rst
  docs/io/configuration/components/plasma.rst
  docs/io/optional/index.rst
  docs/io/output/callback.rst
  docs/io/output/index.rst
  docs/io/output/vpacket_logging.rst
Labels: documentation

#1677 Revert "Port tardis_opacities script from tardisanalysis"
  tardis/analysis/opacities.py
Labels: visualization

#1682 Opacities script with proper credit
  tardis/analysis/opacities.py
Labels: visualization

#1658 add refdata repo selection in template
  azure-pipelines/compare-refdata.yml
  azure-pipelines/release-version.yml
  azure-pipelines/run-unit-tests.yml
  azure-pipelines/templates/default.yml
  azure-pipelines/update-refdata.yml
  docs/development/continuous_integration.rst
Labels: CI-CD

#1674 APE 17 migration
  .github/workflows/documentation-build.yml
  .github/workflows/documentation-preview.yml
  .gitignore
  .gitmodules
  MANIFEST.in
  README.rst
  ah_bootstrap.py
  docs/.nojekyll
  docs/Makefile
  docs/_static/tardis.css
  docs/conf.py
  docs/index.rst
  docs/make.bat
  ez_setup.py
  licenses/LICENSE.rst
  licenses/README.rst
  licenses/TEMPLATE_LICENCE.rst
  pyproject.toml
  scripts/tardis
  setup.cfg
  setup.py
  tardis/__init__.py
  tardis/_astropy_init.py
  tardis/conftest.py
  tardis/io/setup_package.py
  tardis/montecarlo/setup_package.py
  tardis/plasma/setup_package.py
  tardis/scripts/tardis.py
  tardis/simulation/setup_package.py
  tardis/tests/integration_tests/conftest.py
  tardis/tests/integration_tests/plot_helpers.py
  tardis/tests/integration_tests/report.py
  tardis/tests/setup_package.py
  tardis_env3.yml
  tox.ini
Labels: CI-CD, bugfix, install, priority - high :fire:

#1683 prepare release pipeline for CalVer
  azure-pipelines/release-version.yml
  azure-pipelines/run-unit-tests.yml
  setup.py
Labels: CI-CD

#1666 Allowing Spectrum Plotting in the Frequency Domain
  tardis/montecarlo/spectrum.py
Labels: visualization

#1695 Enabling spectrum plotting in the frequency domain
  tardis/montecarlo/spectrum.py
Labels: visualization

#1696 Adding mu and r to virtual packet logging
  docs/io/output/vpacket_logging.rst
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/tests/test_numba_interface.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
Labels: virtual packets

#1680 add docstr-coverage badge
  .github/workflows/docstr-coverage.yml
  README.rst
Labels: CI-CD

#1691 Create profiling directory
  docs/development/index.rst
  docs/development/profiling/cpu_threads_dict_128_threads_1_node.csv
  docs/development/profiling/index.rst
  docs/development/profiling/profiling_example.ipynb
  docs/development/profiling/tardis_example.yml
  docs/development/profiling/tardis_prof.png
  docs/development/profiling/tardis_profiling_threads.ipynb
  docs/development/profiling/threads_dict_128_threads_1_node.csv
  docs/development/tardis_example.yml
Labels: documentation

#1701 Adding Logging Support for Caught Exceptions
  tardis/base.py
  tardis/io/atom_data/base.py
  tardis/io/parsers/csvy.py
  tardis/io/util.py
  tardis/plasma/properties/nlte.py
  tardis/plasma/properties/partition_function.py
  tardis/plasma/properties/radiative_properties.py
  tardis/simulation/base.py
  tardis/util/base.py
Labels: logging

#1686 fix pip install
  setup.cfg
  setup.py
  tardis/scripts/tardis
Labels: CI-CD, conda

#1711 Changed the xlim and the ylabel (From PR #1646)
  docs/quickstart/quickstart.ipynb
Labels: documentation

#1713 fix package data for conda-forge package
  setup.cfg
  tardis/io/setup_package.py
  tardis/montecarlo/setup_package.py
  tardis/simulation/setup_package.py
  tardis/tests/setup_package.py
Labels: conda, install

#1707 Open in VSCode badge
  README.rst
Labels: documentation

#1714 Removed Formatting from Existing Log Messages
  tardis/io/atom_data/util.py
  tardis/plasma/standard_plasmas.py
  tardis/simulation/base.py
Labels: codestyle, logging

#1722 Adding missing import for `IonNumberDensityHeNLTE` in `standard_plasmas.py`
  tardis/plasma/standard_plasmas.py
Labels: plasma

#1716 Small fixes to docs
  docs/io/output/vpacket_logging.rst
  tardis/montecarlo/spectrum.py
Labels: documentation

#1726 display "latest" in doc version
  docs/conf.py
Labels: documentation

#1727 Fixing Quickstart Metadata
  docs/quickstart/quickstart.ipynb
Labels: documentation

#1739 Fixed IPython Displaying the Plasma Stratification (Table) even when the Logger is turned Off
  tardis/io/logger/logger.py
Labels: bugfix, documentation, logging

#1737 Add Jaladh to mailmap
  .mailmap
Labels: CI-CD

#1736 Fixing Doc Build Warnings
  docs/conf.py
  docs/credits.rst
  docs/development/azure_links.inc
  docs/development/code_quality.rst
  docs/development/continuous_integration.rst
  docs/development/git_workflow.rst
  docs/index.rst
  docs/installation.rst
  docs/io/configuration/components/atomic/atomic_data_description.rst
  docs/io/configuration/components/debug.rst
  docs/io/configuration/components/index.rst
  docs/outdated/old_gui.rst
  docs/scripts/index.rst
  tardis/io/atom_data/base.py
  tardis/io/logger/logger.py
  tardis/scripts/cmfgen2tardis.py
Labels: documentation

#1730 Renamed `log_state` to `log_level` for setting the logging level in the Logger
  docs/io/optional/logging_configuration.ipynb
  tardis/base.py
  tardis/io/logger/logger.py
  tardis/io/logger/tests/test_logging.py
  tardis/io/schemas/debug.yml
Labels: logging

#1746 Fixing Docs Build
  docs/quickstart/quickstart.ipynb
Labels: documentation

#1743 Fix for Unresponsive Main Page due to Twitter Widget
  docs/news.rst
Labels: documentation

#1723 Edit docstring in `run_tardis`
  tardis/base.py
Labels: documentation

#1636 Adding Convergence Plots
  docs/io/visualization/convergence_plot.ipynb
  tardis/base.py
  tardis/simulation/base.py
  tardis/visualization/__init__.py
  tardis/visualization/tools/convergence_plot.py
  tardis/visualization/tools/tests/__init__.py
  tardis/visualization/tools/tests/test_convergence_plot.py
  tardis/visualization/widgets/shell_info.py
Labels: new feature 🚧, visualization

#1697 Interact Button in Documentation
  docs/conf.py
Labels: documentation

#1740 Renamed `montecarlo_logger.py` to `montecarlo_tracking.py`
  tardis/io/logger/montecarlo_tracking.py
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
Labels: logging, montecarlo, restructure

#1738 TARDIS Grid
  docs/index.rst
  docs/io/grid/TardisGridTutorial.ipynb
  docs/io/grid/example.yml
  docs/io/grid/example_grid.txt
  tardis/grid/__init__.py
  tardis/grid/base.py
  tardis/grid/test.yml
  tardis/grid/tests/data/example.yml
  tardis/grid/tests/data/example_grid.txt
  tardis/grid/tests/test_grid.py
Labels: configuration, new feature 🚧

#1753 Adding Convergence Plots to the Documentation
  docs/io/visualization/convergence_plot.ipynb
  docs/io/visualization/index.rst
Labels: documentation, visualization
