Repository tardis-sn/tardis, pull requests merged in 2021-01, with the labels that each got.

#1393 Update environment file
  tardis/__init__.py
  tardis_env3.yml
Labels: conda

#1399 fix tests with --generate-reference flag
  tardis/montecarlo/tests/test_spectrum.py
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/simulation/tests/test_simulation.py
  tardis/tests/test_tardis_full.py
Labels: CI-CD, priority - high :fire:

#1398 add black check workflow
  .github/workflows/black-check.yml
  tardis/gui/datahandler.py
  tardis/gui/interface.py
  tardis/gui/widgets.py
  tardis/io/config_reader.py
  tardis/io/decay.py
  tardis/io/util.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/ion_population.py
  tardis/widgets/tests/test_shell_info.py
Labels: CI-CD

#1415 Add .log to gitignore, disabled montecarlo log
  .gitignore
  tardis/montecarlo/montecarlo_numba/montecarlo_logger.py
Labels: bugfix, io

#1410 Post reference data results
  azure-pipelines/compare-refdata.yml
Labels: CI-CD

#1403 Fixing Hyperlinks in Documentation
  docs/development/issues.rst
  docs/installation.rst
  docs/physics/montecarlo/basicprinciples.rst
  docs/physics/montecarlo/estimators.rst
  docs/physics/montecarlo/lineinteraction.rst
  docs/physics/montecarlo/propagation.rst
  docs/physics/montecarlo/virtualpackets.rst
  docs/physics/old_physics/index.rst
  docs/physics/old_physics/montecarlo_old.rst
  docs/physics/old_physics/old_plasma.rst
  docs/physics/plasma/index.rst
  docs/physics/plasma/macroatom.rst
  docs/physics/plasma/nebular_plasma.rst
  docs/physics/plasma/nlte.rst
  docs/using/components/atomic/current_public_table.rst
  docs/using/components/models/examples/examples.rst
  docs/using/components/models/index.rst
  docs/using/interaction/hdf_writer.ipynb
  docs/using/interaction/integrator.ipynb
  docs/using/interaction/physical_quantities.ipynb
  docs/using/interaction/to_hdf.rst
  docs/using/interaction/to_hdf_notebook.ipynb
Labels: documentation

#1420 Conversion of enlisted variable to int64 datatype
  tardis/montecarlo/montecarlo_numba/base.py
Labels: bugfix, numba

#1421 Old physics reorganization
  docs/index.rst
  docs/physics/montecarlo/estimators.rst
  docs/physics/old_physics/index.rst
  docs/physics/old_physics/old_plasma.rst
  docs/physics/plasma.rst
  docs/physics/plasma/index.rst
  docs/using/components/configuration/configuration.rst
Labels: documentation

#1405 Restructured development workflow and added code quality & documentation guidelines in it
  CONTRIBUTING.md
  docs/development/code_quality.rst
  docs/development/documentation_guidelines.rst
  docs/development/documentation_preview.rst
  docs/development/git_workflow.rst
  docs/development/index.rst
  docs/index.rst
  docs/installation.rst
  docs/research/research_done_using_TARDIS/ads.ipynb
  docs/research/research_done_using_TARDIS/research_papers.rst
  docs/roadmap.rst
Labels: codestyle, documentation, priority - high :fire:

#1409 add docstr-coverage workflow
  .docstr.yaml
  .github/workflows/docstr-coverage.yml
Labels: CI-CD, Work in progress

#1424 Rename Kromer Plot to Spectral Element Decomposition (SEDec) Plot
  tardis/widgets/__init__.py
  tardis/widgets/sedec_plot.py
Labels: bugfix, priority - medium

#1431 Documentation guidelines hotfix
  docs/development/code_quality.rst
Labels: bugfix, priority - high :fire:

#1430 compare refdata with arbitrary labels
  azure-pipelines/compare-refdata.yml
  docs/development/continuous_integration.rst
Labels: CI-CD

#1441 Rename SEDec to SDEC in Spectral element DEComposition plot
  tardis/widgets/__init__.py
  tardis/widgets/sdec_plot.py
Labels: priority - high :fire:, visualization

#1432 fix update changelog workflow
  .github/workflows/documentation-build.yml
  .github/workflows/update-changelog.yml
Labels: CI-CD
