Repository tardis-sn/tardis, pull requests merged in 2021-02, with the labels that each got.

#1442 Fixed distance parameter not producing accurate SDEC plots
  tardis/widgets/sdec_plot.py
Labels: bugfix, visualization

#1455 Clean up numba parallelization warnings #1416
  tardis/montecarlo/montecarlo_numba/__init__.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/macro_atom.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
Labels: bugfix, numba

#1446 Fixed italicised Units in sdec_plot
  tardis/widgets/sdec_plot.py
Labels: bugfix, visualization

#1454 Reorganizing Models
  docs/using/components/models/abundancecust/abund.dat
  docs/using/components/models/abundancecust/abundancecust.rst
  docs/using/components/models/abundancecust/tardis_configv1_abundance_cust_example.yml
  docs/using/components/models/abundancecust/tardis_configv1_isotope_abundance_cust_example.yml
  docs/using/components/models/abundancecust/tardis_model_abund.csv
  docs/using/components/models/abundanceuni/abundanceuni.rst
  docs/using/components/models/abundanceuni/tardis_configv1_abundance_uniform_example.yml
  docs/using/components/models/csvy_full_rad.csvy
  docs/using/components/models/csy/csvy_test.ipynb
  docs/using/components/models/densitycust/Custom_Density_And_Boundary_Velocities.ipynb
  docs/using/components/models/densitycust/density.dat
  docs/using/components/models/densitycust/densitycust.rst
  docs/using/components/models/densitycust/tardis_configv1_density_cust_example.yml
  docs/using/components/models/densitycust/test_abund.dat
  docs/using/components/models/densitycust/test_config.yml
  docs/using/components/models/densitycust/test_config_ex1.yml
  docs/using/components/models/densitycust/test_config_ex2.yml
  docs/using/components/models/densitycust/test_config_ex3.yml
  docs/using/components/models/densitycust/test_density.txt
  docs/using/components/models/densityexp/densityexp.rst
  docs/using/components/models/densityexp/tardis_configv1_density_exponential_example.yml
  docs/using/components/models/densitypow/densitypow.rst
  docs/using/components/models/densitypow/tardis_configv1_density_power_law_example.yml
  docs/using/components/models/examples/examples.rst
  docs/using/components/models/examples/index.rst
  docs/using/components/models/examples/modelconfig.rst
  docs/using/components/models/examples/run_simple_example.ipynb
  docs/using/components/models/examples/tardis_example.rst
  docs/using/components/models/index.rst
Labels: documentation

#1464 Fixed the array types when interpolate_shells > 0. Now returns the p…
  tardis/montecarlo/formal_integral.py
Labels: bugfix, easy, formal integral, montecarlo, priority - high :fire:
