Repository tardis-sn/tardis, pull requests merged in 2022-11, with the labels that each got.

#2146 Add missing cell to download atom data
  docs/io/visualization/montecarlo_packet_visualization.ipynb
Labels: documentation, build-docs

#2127 Possible fix for prerelease workflow
  .github/workflows/pre-release.yml
Labels: CI/CD

#2147 Pin setuptools_scm to v6
  .github/workflows/release.yml
  tardis_env3.yml
Labels: infrastructure, build-docs

#2152 Set specific qgrid feedstock version
  tardis_env3.yml
Labels: bugfix :beetle:, priority - high :fire:, install

#2159 Fix relativistic packet initialization
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/montecarlo/packet_source.py
  tardis/transport/r_packet_transport.py
Labels: virtual packets, relativity

#2154 Fixing typos for nlte ion
  tardis/plasma/properties/nlte_rate_equation_solver.py
  tardis/plasma/properties/rate_matrix_index.py
Labels: priority - low :snail:
