Repository tardis-sn/tardis, pull requests merged in 2022-02, with the labels that each got.

#1893 Fixing small docs issues
  .gitignore
  docs/io/configuration/components/models/converters/arepo_snapshot.hdf5
  docs/io/configuration/components/models/converters/arepo_to_tardis.ipynb
  docs/io/configuration/components/spectrum.rst
  tardis/io/parsers/arepo.py
Labels: documentation

#1868 Fixing Plasma Graph to Allow .dot and .tex file Generation
  docs/physics/setup/plasma/index.rst
  tardis/plasma/base.py
Labels: plasma, documentation

#1891 Fixing Broken Latex Code
  docs/physics/setup/plasma/helium_nlte.rst
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/ion_population.py
Labels: bugfix, documentation

#1837 CUDA Version of the Formal Integral
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/formal_integral_cuda.py
  tardis/montecarlo/montecarlo_numba/tests/test_cuda_formal_integral.py
Labels: Work in progress, formal integral, numba-montecarlo, new feature 🚧

#1900 Make update-refdata pipeline open a PR instead of merging changes
  .azure-pipelines/update-refdata.yml
Labels: CI-CD

#1710 Changed Formatting for the logger based on Log Level
  tardis/io/atom_data/base.py
  tardis/io/atom_data/util.py
  tardis/io/logger/colored_logger.py
  tardis/io/logger/logger.py
  tardis/plasma/standard_plasmas.py
  tardis/simulation/base.py
Labels: logging

#1886 Continuum branch [attempted merge with master]
  tardis/io/logger/tests/test_logging.py
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_configuration.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/calculate_distances.py
  tardis/montecarlo/montecarlo_numba/estimators.py
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/frame_transformations.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/macro_atom.py
  tardis/montecarlo/montecarlo_numba/numba_config.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/r_packet_transport.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/tests/conftest.py
  tardis/montecarlo/montecarlo_numba/tests/test_interaction.py
  tardis/montecarlo/montecarlo_numba/tests/test_macro_atom.py
  tardis/montecarlo/montecarlo_numba/tests/test_numba_interface.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
  tardis/montecarlo/montecarlo_numba/tests/test_vpacket.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/continuum_processes.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/properties/radiative_properties.py
  tardis/plasma/properties/transition_probabilities.py
  tardis/plasma/standard_plasmas.py
  tardis/simulation/base.py
Labels: priority - high :fire:, new feature 🚧

#1914 add continuum tracer
  tardis/montecarlo/montecarlo_numba/continuum/__init__.py
  tardis/montecarlo/montecarlo_numba/continuum/r_packet_transport_continuum.py
Labels: montecarlo

#1823 Disable Convergence Plots by default
  tardis/base.py
Labels: visualization
