Repository tardis-sn/tardis, pull requests merged in 2022-07, with the labels that each got.

#2082 Added documetation on how to compare environment before update
  docs/installation.rst
Labels: documentation

#2084 Fix broken links in workflow files and goverance md
  .azure-pipelines/compare-refdata.yml
  .azure-pipelines/templates/default.yml
  .azure-pipelines/update-refdata.yml
  .github/workflows/build-docs.yml
  .github/workflows/clean-docs.yml
  .github/workflows/codestyle.yml
  .github/workflows/mailmap.yml
  .github/workflows/post-release.yml
  .github/workflows/pre-release.yml
  GOVERNANCE.md
Labels: bugfix :beetle:, documentation

#1941 Improved arepo parser
  .ci-helpers/download_reference_data.sh
  docs/io/configuration/components/models/converters/arepo_snapshot.json
  docs/io/configuration/components/models/converters/arepo_to_tardis.ipynb
  tardis/io/parsers/arepo.py
  tardis/io/tests/data/arepo_cone_reference_model.csvy
  tardis/io/tests/data/arepo_full_reference_model.csvy
  tardis/io/tests/data/arepo_line_reference_model.csvy
  tardis/io/tests/test_arepo_parser.py
Labels: io

#2088 Arepo docs fix
  .mailmap
  docs/io/configuration/components/models/converters/arepo_to_tardis.ipynb
Labels: build-docs

#2104 Re-produced PR 1826
  tardis/visualization/widgets/tests/test_custom_abundance.py
Labels: testing :vertical_traffic_light:, visualization
