Repository tardis-sn/tardis, pull requests merged in 2022-01, with the labels that each got.

#1846 Fix Virtual Packet Logging Bug
  tardis/montecarlo/montecarlo_numba/base.py
Labels: virtual packets, numba-montecarlo

#1848 Switching progress bars page to rst
  docs/io/output/progress_bars.ipynb
  docs/io/output/progress_bars.rst
Labels: documentation

#1752 Add tests to SDEC plotter module
  tardis/visualization/tools/tests/data/observed_spectrum_test_data.dat
  tardis/visualization/tools/tests/test_sdec_plot.py
Labels: Work in progress, priority - high :fire:, visualization

#1861 Renamed `RPacketCollection` Class to `RPacketTracker`
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/tests/test_montecarlo.py
Labels: logging

#1866 Refactor `test_configuration_namespace.py`
  tardis/io/tests/test_configuration_namespace.py
Labels: testing

#1865 Fixing links on contributing page
  CONTRIBUTING.md
Labels: documentation

#1847 Add a ModelState class
  tardis/model/base.py
  tardis/model/tests/test_base.py
Labels: restructure

#1872 Fix links in the code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#1876 fixed outdated pytest tardis command in documentation
  docs/contributing/development/running_tests.rst
Labels: documentation, testing

#1849 Interactive docs for models
  docs/graphics/dilution_factor.png
  docs/io/configuration/components/models/abundanceuni/abundanceuni.rst
  docs/io/configuration/components/models/abundanceuni/tardis_configv1_abundance_uniform_example.yml
  docs/io/configuration/components/models/densityexp/densityexp.rst
  docs/io/configuration/components/models/densityexp/tardis_configv1_density_exponential_example.yml
  docs/io/configuration/components/models/densitypow/densitypow.rst
  docs/io/configuration/components/models/densitypow/tardis_configv1_density_power_law_example.yml
  docs/io/configuration/components/models/index.rst
  docs/io/configuration/read_configuration.ipynb
  docs/physics/images/expansion_animation.gif
  docs/physics/montecarlo/propagation.rst
  docs/physics/setup/index.rst
  docs/physics/setup/model.ipynb
  docs/physics/setup/model.rst
  docs/physics/setup/setup_example.ipynb
  docs/physics/setup/tardis_example.yml
  tardis/io/schemas/base.yml
Labels: documentation

#1843 Changed Default Log Level to `INFO` for the Simulation Logging
  tardis/io/logger/logger.py
Labels: bugfix, logging

#1877 printing packet information
  tardis/montecarlo/montecarlo_numba/calculate_distances.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
Labels: numba, logging
