Repository tardis-sn/tardis, pull requests merged in 2022-05, with the labels that each got.

#1989 Pre-release workflow
  .github/workflows/pre-release.yml
  .github/workflows/update-changelog.yml
  .github/workflows/update-zenodo-json.yml
Labels: conda, CI-CD

#1987 Better documentation build workflow from 2021 GA Hackathon
  .github/workflows/build-docs.yml
  .github/workflows/clean-docs.yml
  .github/workflows/documentation-build.yml
  .github/workflows/documentation-preview.yml
Labels: documentation, CI-CD

#2000 Make docs build in parallel
  .github/workflows/build-docs.yml
Labels: build-docs

#2001 Post-release workflow
  .github/workflows/post-release.yml
  CITATION.cff
Labels: CI-CD

#1999 Create TARDIS release workflow
  .azure-pipelines/release-version.yml
  .github/workflows/release.yml
Labels: CI-CD

#1995 Force constant version date length
  .ci-helpers/get_current_version.py
  .ci-helpers/get_next_version.py
Labels: infrastructure

#2003 Fix for isotope abundance parsing
  tardis/plasma/standard_plasmas.py
Labels: model, priority - high :fire:, build-docs

#2009 Revert "Removing Levels Index Variable Within Atomic Data Preperation"
  tardis/io/atom_data/base.py
Labels: bugfix

#2008 Move link_t_rad_t_electron to config file
  .mailmap
  tardis/io/schemas/plasma.yml
  tardis/plasma/standard_plasmas.py
Labels: plasma

#2007 Use `pull_request_target` trigger in release workflow
  .github/workflows/release.yml
Labels: CI-CD

#2012 Fix post-release workflow automation
  .github/workflows/post-release.yml
  .github/workflows/pre-release.yml
Labels: CI-CD

#1996 Fixes for compare-refdata pipeline
  .azure-pipelines/compare-refdata.yml
  .azure-pipelines/templates/default.yml
Labels: priority - high :fire:, CI-CD

#2019 Added compatability to current version of carsus atomic data
  tardis/io/atom_data/base.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/continuum_processes.py
Labels: plasma, atomic, bugfix, opacity

#2030 Fix estimators parallel
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
Labels: priority - high :fire:, numba, numba-montecarlo

#1921 Formal integral documentation
  docs/physics/est_and_conv/estimators.ipynb
  docs/physics/images/formal_integral_2d.ggb
  docs/physics/images/formal_integral_2d_above.png
  docs/physics/images/formal_integral_2d_below.png
  docs/physics/images/formal_integral_sphere.ggb
  docs/physics/images/formal_integral_sphere.jpg
  docs/physics/montecarlo/propagation.rst
  docs/physics/spectrum/basic.ipynb
  docs/physics/spectrum/formal_integral.rst
  docs/physics/spectrum/index.rst
  docs/physics/spectrum/sourceintegration.rst
  tardis/montecarlo/montecarlo_numba/formal_integral.py
Labels: documentation, formal integral

#2020 Fixes for CITATION.cff
  .github/workflows/post-release.yml
Labels: CI-CD

#2027 Switch from `docstr-coverage` package to `interrogate` in CI pipelines
  .ci-helpers/get_min_docstr_cov.py
  .docstr.yaml
  .github/workflows/docstr-cov.yml
  pyproject.toml
Labels: CI-CD

#2024 Added v_inner and v_outer, enable_nonhomologous_expansion for future use in nonhomologous expansion
  tardis/io/schemas/montecarlo.yml
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/tests/conftest.py
  tardis/montecarlo/montecarlo_numba/tests/test_cuda_formal_integral.py
  tardis/montecarlo/montecarlo_numba/tests/test_numba_formal_integral.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
Labels: model, feature
