Repository tardis-sn/tardis, pull requests merged in 2022-04, with the labels that each got.

#1925 Plasma Graph Tutorial
  .gitignore
  docs/io/output/default_plasma_graph.png
  docs/io/output/index.rst
  docs/io/output/plasma_graph.ipynb
  docs/io/output/plasma_graph_args.png
  docs/io/output/plasma_graph_no_eq.png
  docs/io/output/plasma_graph_scaled.png
  docs/physics/setup/plasma/index.rst
Labels: plasma, documentation

#1813 Replacing PyNE with radioactivedecay for radionuclide decay calculations
  tardis/__init__.py
  tardis/io/decay.py
  tardis/io/logger/logger.py
  tardis/io/model_reader.py
  tardis/io/tests/test_decay.py
  tardis/model/base.py
  tardis/util/base.py
  tardis/visualization/widgets/custom_abundance.py
  tardis_env3.yml
Labels: atomic, priority - high :fire:, restructure

#1959 Disable `mamba` on Azure Pipelines
  .azure-pipelines/compare-refdata.yml
  .azure-pipelines/release-version.yml
  .azure-pipelines/run-unit-tests.yml
  .azure-pipelines/update-refdata.yml
Labels: bugfix, priority - high :fire:, CI-CD

#1968 fixed index typo in Saha solver documentation
  docs/physics/setup/plasma/lte_plasma.rst
Labels: priority - low, documentation

#1957 Removing Levels Index Variable Within Atomic Data Preperation
  tardis/io/atom_data/base.py
Labels: plasma

#1948 Update TARDIS environment after replacing PyNE
  .github/workflows/black-check.yml
  tardis/__init__.py
  tardis/analysis/opacities.py
  tardis/gui/tests/test_gui.py
  tardis/montecarlo/base.py
  tardis/visualization/tools/sdec_plot.py
  tardis_env3.yml
Labels: priority - high :fire:, conda, infrastructure

#1933 Intensity p rays
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/formal_integral_cuda.py
  tardis/montecarlo/montecarlo_numba/tests/test_cuda_formal_integral.py
Labels: feature request, formal integral

#1970 Remove pull request bot comment workflow
  .github/workflows/pr_review_checklist.yml
Labels: CI-CD

#1974 Add disclaimer to environment file regarding conda-forge recipe
  tardis_env3.yml
Labels: priority - high :fire:, conda, CI-CD

#1973 Use spec file on Zenodo pipeline
  .github/workflows/update-zenodo-json.yml
  .mailmap
Labels: documentation, CI-CD

#1982 Add bot comment with directions to update .mailmap
  .github/workflows/mailmap-check.yml
  .github/workflows/mailmap.yml
Labels: CI-CD

#1980 Check Black format on `master` branch
  .github/workflows/black.yml
Labels: CI-CD

#1981 Better docstring coverage workflow from 2021 GA Hackathon
  .github/workflows/docstr-cov.yml
  .github/workflows/docstr-coverage.yml
  README.rst
Labels: documentation, CI-CD

#1985 Migrate testing pipeline to GitHub Actions
  .azure-pipelines/run-unit-tests.yml
  .github/workflows/tests.yml
  README.rst
Labels: CI-CD

#1978 Plasma number densities using isotopes
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/general.py
  tardis/plasma/properties/plasma_input.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/standard_plasmas.py
  tardis/plasma/tests/test_tardis_model_density_config.py
Labels: plasma, priority - high :fire:, nebular, new feature 🚧

#1988 Use Azure mirror for reference data in testing pipeline
  .azure-pipelines/compare-refdata.yml
  .ci-helpers/download_reference_data.sh
  .github/workflows/tests.yml
Labels: priority - high :fire:, CI-CD
