Repository tardis-sn/tardis, pull requests merged in 2022-06, with the labels that each got.

#2039 Check PEP8 on CI
  .github/workflows/black.yml
  .github/workflows/codestyle.yml
Labels: CI-CD

#1698 Gamma ray propagation
  docs/index.rst
  docs/physics/energy_input/gammaray_deposition.ipynb
  docs/physics/energy_input/index.rst
  tardis/energy_input/GXPacket.py
  tardis/energy_input/calculate_opacity.py
  tardis/energy_input/energy_source.py
  tardis/energy_input/gamma_ray_estimators.py
  tardis/energy_input/gamma_ray_grid.py
  tardis/energy_input/gamma_ray_interactions.py
  tardis/energy_input/indivisible_packets.py
  tardis/energy_input/nuclear_energy_source.py
  tardis/energy_input/tests/conftest.py
  tardis/energy_input/tests/test_calculate_opacity.py
  tardis/energy_input/tests/test_energy_source.py
  tardis/energy_input/tests/test_gamma_ray_grid.py
  tardis/energy_input/tests/test_gamma_ray_interactions.py
  tardis/energy_input/tests/test_util.py
  tardis/energy_input/util.py
  tardis/io/tests/data/tardis_configv1_density_exponential_nebular.yml
Labels: nebular, feature

#2047 Ignore gamma-ray deposition notebook for now
  docs/conf.py
Labels: bugfix :beetle:, documentation, build-docs

#2010 Enable automerge on pre and post-release workflows
  .github/workflows/build-docs.yml
  .github/workflows/post-release.yml
  .github/workflows/pre-release.yml
Labels: CI/CD

#2042 Polish up Quickstart guide
  docs/conf.py
  docs/installation.rst
  docs/quickstart.ipynb
Labels: documentation, build-docs

#2048 Disable profiling page build on pull requests
  .github/workflows/build-docs.yml
  docs/conf.py
Labels: documentation, CI/CD, build-docs

#2053 Change developer installation command
  docs/installation.rst
Labels: documentation, build-docs

#2036 Restructure code to remove the single_packet_seed field
  .mailmap
  docs/contributing/development/debug_numba.rst
  tardis/io/schemas/montecarlo.yml
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_configuration.py
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/scripts/debug/run_numba_single.py
  tardis/scripts/debug/tardis_example_single.yml
Labels: bugfix :beetle:, numba-montecarlo

#2063 Initial geometry restructure
  .mailmap
  tardis/montecarlo/montecarlo_numba/continuum/r_packet_transport_continuum.py
  tardis/montecarlo/montecarlo_numba/r_packet_transport.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/transport/calculate_distances.py
Labels: restructure

#2065 Continuing geometry restructure
  tardis/montecarlo/montecarlo_numba/continuum/r_packet_transport_continuum.py
  tardis/montecarlo/montecarlo_numba/estimators.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
  tardis/montecarlo/montecarlo_numba/tests/test_vpacket.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/montecarlo/tests/test_montecarlo.py
  tardis/transport/frame_transformations.py
  tardis/transport/r_packet_transport.py
Labels: restructure

#2050 Update Jsonschema package to V4
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  tardis/io/config_validator.py
  tardis_env3.yml
Labels: configuration, build-docs

#2069 Wait for pull request creation
  .github/workflows/post-release.yml
  .github/workflows/pre-release.yml
Labels: CI/CD, build-docs

#2062 Remove yaml_load_config_file
  .mailmap
  tardis/__init__.py
  tardis/conftest.py
  tardis/io/util.py
Labels: restructure
