Repository tardis-sn/tardis, pull requests merged in 2023-01, with the labels that each got.

#2187 Downloading nlte_atom_data in ref data
  .ci-helpers/download_reference_data.sh
Labels: bugfix :beetle:

#2171 Adding nlte solver
  tardis/io/tests/data/tardis_configv1_nlte.yml
  tardis/plasma/properties/nlte_rate_equation_solver.py
  tardis/plasma/properties/transition_probabilities.py
  tardis/plasma/tests/test_nlte_solver.py
Labels: plasma

#2185 Rename T variables to temperature
  .mailmap
  tardis/analysis/opacities.py
  tardis/montecarlo/base.py
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/formal_integral_cuda.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/tests/test_cuda_formal_integral.py
  tardis/montecarlo/montecarlo_numba/tests/test_numba_formal_integral.py
  tardis/montecarlo/packet_source.py
  tardis/plasma/properties/continuum_processes.py
  tardis/util/base.py
Labels: codestyle

#2198 Fixing test_store_runner_to_hdf
  tardis/io/tests/test_model_reader.py
Labels: bugfix :beetle:

#2195 Reading nlte_excitation_species from config
  tardis/io/tests/test_config_reader.py
  tardis/plasma/properties/plasma_input.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/properties/rate_matrix_index.py
  tardis/plasma/standard_plasmas.py
  tardis/plasma/tests/test_nlte_solver.py
  tardis/tests/fixtures/atom_data.py
Labels: plasma
