Repository tardis-sn/tardis, pull requests merged in 2023-07, with the labels that each got.

#2327 Refactor Model Reader on the Stella example
  docs/index.rst
  docs/io/configuration/components/models/converters/stella_to_tardis.ipynb
  docs/io/configuration/components/models/index.rst
  docs/io/model/index.rst
  docs/io/model/mesa.stella.dat
  docs/io/model/read_stella_model.ipynb
  tardis/io/model/__init__.py
  tardis/io/model/stella.py
  tardis/io/model/tests/data/mesa.stella.dat
  tardis/io/model/tests/test_model_io.py
  tardis/io/parsers/stella.py
Labels: io, restructure, build-docs

#2139 Gamma ray refactor
  tardis/energy_input/GXPacket.py
  tardis/energy_input/calculate_opacity.py
  tardis/energy_input/energy_source.py
  tardis/energy_input/gamma_packet_loop.py
  tardis/energy_input/gamma_ray_estimators.py
  tardis/energy_input/gamma_ray_grid.py
  tardis/energy_input/gamma_ray_interactions.py
  tardis/energy_input/gamma_ray_transport.py
  tardis/energy_input/indivisible_packets.py
  tardis/energy_input/samplers.py
  tardis/energy_input/tests/test_energy_source.py
  tardis/energy_input/util.py
  tardis/montecarlo/montecarlo_numba/opacities.py
  tardis/montecarlo/montecarlo_numba/tests/test_opacities.py
Labels: nebular, restructure

#2347 Fix frame transformations of continuum opacity
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
Labels: relativity, bugfix :beetle:, numba-montecarlo, build-docs

#2359 Rename NumbaPlasma to OpacityState
  tardis/montecarlo/montecarlo_numba/base.py
  tardis/montecarlo/montecarlo_numba/formal_integral.py
  tardis/montecarlo/montecarlo_numba/interaction.py
  tardis/montecarlo/montecarlo_numba/macro_atom.py
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/montecarlo/montecarlo_numba/opacities.py
  tardis/montecarlo/montecarlo_numba/r_packet.py
  tardis/montecarlo/montecarlo_numba/single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/tests/conftest.py
  tardis/montecarlo/montecarlo_numba/tests/test_cuda_formal_integral.py
  tardis/montecarlo/montecarlo_numba/tests/test_interaction.py
  tardis/montecarlo/montecarlo_numba/tests/test_macro_atom.py
  tardis/montecarlo/montecarlo_numba/tests/test_numba_interface.py
  tardis/montecarlo/montecarlo_numba/tests/test_packet.py
  tardis/montecarlo/montecarlo_numba/tests/test_single_packet_loop.py
  tardis/montecarlo/montecarlo_numba/tests/test_vpacket.py
  tardis/montecarlo/montecarlo_numba/vpacket.py
  tardis/transport/r_packet_transport.py
Labels: restructure, opacity, build-docs

#2361 add deprecated decorator
  tardis/util/base.py
Labels: restructure
