Repository tardis-sn/tardis, pull requests merged in 2023-02, with the labels that each got.

#2200 Fix config reader tests
  tardis/io/tests/test_config_reader.py
Labels: bugfix :beetle:, testing :vertical_traffic_light:

#2190 Add version tag to simulation objects
  .mailmap
  tardis/simulation/base.py
  tardis/simulation/tests/test_simulation.py
Labels: feature

#2214 Correct the description of 'no_of_packets' in Monte Carlo Configuration
  tardis/io/schemas/montecarlo.yml
Labels: documentation

#2204 Add docstrings to subpackages
  .mailmap
  tardis/analysis.py
  tardis/base.py
  tardis/grid/__init__.py
  tardis/gui/__init.py__
  tardis/gui/__init__.py
  tardis/io/__init__.py
  tardis/io/atom_data/__init__.py
  tardis/io/logger/__init__.py
  tardis/io/parsers/__init__.py
  tardis/model/__init__.py
  tardis/model/geometry/__init__.py
  tardis/montecarlo/__init__.py
  tardis/montecarlo/montecarlo_numba/__init__.py
  tardis/plasma/__init__.py
  tardis/plasma/properties/__init__.py
  tardis/plasma/properties/util/__init__.py
  tardis/scripts/__init__.py
  tardis/simulation/__init__.py
  tardis/stats/__init__.py
  tardis/transport/__init__.py
  tardis/transport/geometry/__init__.py
  tardis/util/__init__.py
Labels: documentation
