Repository tardis-sn/tardis, pull requests merged in 2023-04, with the labels that each got.

#2249 Port update reference data pipeline to GitHub Actions
  .azure-pipelines/update-refdata.yml
  .github/workflows/dispatcher.yml
  .github/workflows/update-refdata.yml
  tardis/conftest.py
  tardis/io/tests/test_arepo_parser.py
Labels: CI/CD, build-docs

#2273 Fixes for update reference data workflow
  .github/workflows/update-refdata.yml
Labels: CI/CD, build-docs

#2267 Check MD5 sums of downloaded atom data
  tardis/data/atomic_data_repo.yml
  tardis/io/atom_data/atom_web_download.py
  tardis/io/util.py
Labels: documentation, CI/CD, build-docs

#2280 Prevent tests from running on forks
  .github/workflows/tests.yml
Labels: priority - high :fire:, testing :vertical_traffic_light:, CI/CD
