Repository tardis-sn/tardis, pull requests merged in 2023-11, with the labels that each got.

#2458 Enable nlte ionization as plasma component
  docs/io/configuration/components/plasma.rst
  docs/physics/setup/plasma/index.rst
  tardis/montecarlo/montecarlo_numba/numba_interface.py
  tardis/plasma/properties/nlte_rate_equation_solver.py
  tardis/plasma/properties/transition_probabilities.py
  tardis/plasma/standard_plasmas.py
  tardis/plasma/tests/test_nlte_solver.py
Labels: configuration, feature, build-docs

#2462 Update docstr-cov.yml to fix failing action
  .github/workflows/docstr-cov.yml
Labels: bugfix :beetle:, CI/CD

#2413 Tests Plasma Using Syrupy
  .github/workflows/tests.yml
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  docs/contributing/development/running_tests.rst
  tardis/conftest.py
  tardis/plasma/tests/conftest.py
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/plasma/tests/test_hdf_plasma.py
  tardis/plasma/tests/test_nlte_excitation.py
  tardis/plasma/tests/test_nlte_solver.py
  tardis/plasma/tests/test_plasma_contiuum.py
  tardis/plasma/tests/test_plasma_vboundary.py
  tardis/plasma/tests/test_tardis_model_density_config.py
  tardis/util/syrupy_extensions.py
  tardis_env3.yml
Labels: work in progress 🚧, testing :vertical_traffic_light:, build-docs

#2470 Add astropy import guard
  .mailmap
  tardis/__init__.py
Labels: bugfix :beetle:

#2471 Reading in decay radiation data in atom data
  tardis/data/atomic_data_repo.yml
  tardis/io/atom_data/base.py
Labels: priority - high :fire:, build-docs

#2478 Add ruff rules and docs
  .ruff.toml
  docs/contributing/development/code_quality.rst
  pyproject.toml
Labels: build-docs

#2479 Check if atom data download exists
  tardis/io/atom_data/atom_web_download.py
  tardis/io/configuration/config_internal.py
  tardis/visualization/widgets/shell_info.py
Labels: build-docs
