Repository tardis-sn/tardis, pull requests merged in 2024-11, with the labels that each got.

#2858 Gamma ray documentation introduction
  docs/physics/tardisgamma/index.rst
Labels: documentation

#2871 Fix the issue where the docs are built twice when there are no changes
  .github/workflows/build-docs.yml
Labels: documentation

#2844 Remove integration tests
  tardis/tests/integration_tests/__init__.py
  tardis/tests/integration_tests/at/abundances.dat
  tardis/tests/integration_tests/at/config.yml
  tardis/tests/integration_tests/at/densities.dat
  tardis/tests/integration_tests/conftest.py
  tardis/tests/integration_tests/paper1_downbranch/config.yml
  tardis/tests/integration_tests/paper1_macroatom/abundances.dat
  tardis/tests/integration_tests/paper1_macroatom/config.yml
  tardis/tests/integration_tests/paper1_macroatom/densities.dat
  tardis/tests/integration_tests/paper1_scatter/config.yml
  tardis/tests/integration_tests/runner.py
  tardis/tests/integration_tests/test_integration.py
  tardis/tests/integration_tests/w7/abundances.dat
  tardis/tests/integration_tests/w7/config.yml
  tardis/tests/integration_tests/w7/densities.dat
Labels: testing :vertical_traffic_light:

#2884 Release Fixes
  .github/workflows/post-release.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: CI/CD

#2886 Release Fixes
  .github/workflows/release.yml
Labels: CI/CD

#2891 Revert "Fix the issue where the docs are built twice when there are no changes"
  .github/workflows/build-docs.yml
Labels: CI/CD

#2890 Update badge for doc string coverage
  README_TEMPLATE.rst
Labels: CI/CD
