Repository tardis-sn/tardis, pull requests merged in 2024-10, with the labels that each got.

#2841 Fix navigation sidebar on mobile
  docs/conf.py
Labels: build-docs

#2839 Fix mambaforge issue in STARDIS tests
  .github/workflows/stardis-tests.yml
Labels: CI/CD

#2838 Add zenodo badge in the release summary notes
  .github/workflows/release.yml
Labels: CI/CD

#2845 Ruff `tardis/plasma`
  tardis/plasma/__init__.py
  tardis/plasma/base.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/base.py
  tardis/plasma/properties/continuum_processes/__init__.py
  tardis/plasma/properties/continuum_processes/fast_array_util.py
  tardis/plasma/properties/general.py
  tardis/plasma/properties/helium_nlte.py
  tardis/plasma/properties/ion_population.py
  tardis/plasma/properties/level_population.py
  tardis/plasma/properties/nlte.py
  tardis/plasma/properties/nlte_excitation_data.py
  tardis/plasma/properties/nlte_rate_equation_solver.py
  tardis/plasma/properties/partition_function.py
  tardis/plasma/properties/plasma_input.py
  tardis/plasma/properties/radiative_properties.py
  tardis/plasma/properties/rate_matrix_index.py
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/plasma/tests/test_hdf_plasma.py
  tardis/plasma/tests/test_nlte_excitation.py
  tardis/plasma/tests/test_nlte_solver.py
  tardis/plasma/tests/test_plasma_continuum.py
Labels: codestyle

#2847 Ruff on tardis/simulation
  tardis/simulation/base.py
Labels: codestyle

#2824 fix typo for word boundaries in doc
  .mailmap
  docs/contributing/development/known_projects.inc
  docs/contributing/tools/hdf_writer.ipynb
  docs/contributing/tools/profiling/tardis_profiling_threads.ipynb
  docs/io/configuration/components/models/converters/arepo_to_tardis.ipynb
  docs/io/configuration/components/models/csvy_full_rad.csvy
  docs/resources/code_comparison/toy_models/blondin_compare.csvy
  docs/resources/code_comparison/toy_models/blondin_compare_01.csvy
  docs/resources/code_comparison/toy_models/blondin_compare_06.csvy
Labels: documentation

#2855 Remove black from docs and update with ruff
  README_TEMPLATE.rst
  docs/_static/ruff_badge.json
  docs/contributing/development/code_quality.rst
  docs/contributing/development/developer_faq.rst
Labels: documentation, codestyle

#2854 Remove black from environment yml and lock files.
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  conda-osx-arm64.lock
  tardis_env3.yml
Labels: conda, codestyle

#2851 Fix codespell
  .github/workflows/codespell.yml
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  conda-osx-arm64.lock
  tardis_env3.yml
Labels: CI/CD

#2833 Pytest Warnings Fix - 2
  pyproject.toml
  tardis/energy_input/util.py
  tardis/io/model/parse_radiation_field_configuration.py
  tardis/io/tests/test_atomic.py
  tardis/model/matter/composition.py
  tardis/plasma/properties/atomic.py
  tardis/plasma/properties/nlte_rate_equation_solver.py
  tardis/visualization/widgets/shell_info.py
Labels: codestyle, build-docs

#2770 Restructure/detailed balance foundation
  docs/physics/plasma/detailed_balance/collisional_rate_coefficients.hdf
  docs/physics/plasma/detailed_balance/comparison.ipynb
  docs/physics/plasma/detailed_balance/rates.ipynb
  docs/physics/plasma/detailed_balance/test_continuum_template_wkerzen_rate_coeffs.yml
  tardis/plasma/assembly/base.py
  tardis/plasma/assembly/legacy_assembly.py
  tardis/plasma/detailed_balance/__init__.py
  tardis/plasma/detailed_balance/rates/__init__.py
  tardis/plasma/detailed_balance/rates/collision_strengths.py
  tardis/plasma/detailed_balance/rates/collisional_rates.py
  tardis/plasma/detailed_balance/rates/radiative_rates.py
  tardis/plasma/detailed_balance/tests/__init__.py
  tardis/plasma/detailed_balance/tests/test_collisional_transitions.py
  tardis/plasma/properties/nlte_rate_equation_solver.py
  tardis/plasma/radiation_field/__init__.py
Labels: plasma, restructure

#2849 Ruff root files
  tardis/__init__.py
  tardis/_astropy_init.py
  tardis/base.py
  tardis/scripts/cmfgen2tardis.py
  tardis/tests/fixtures/atom_data.py
  tardis/tests/integration_tests/conftest.py
  tardis/tests/integration_tests/test_integration.py
  tardis/tests/test_util.py
Labels: codestyle

#2848 Ruff `tardis/spectrum`
  tardis/spectrum/formal_integral.py
  tardis/spectrum/formal_integral_cuda.py
  tardis/spectrum/tests/test_cuda_formal_integral.py
  tardis/spectrum/tests/test_numba_formal_integral.py
  tardis/spectrum/tests/test_spectrum.py
Labels: codestyle

#2843 Close regression data files
  tardis/spectrum/tests/test_spectrum_solver.py
  tardis/tests/fixtures/regression_data.py
  tardis/tests/test_tardis_full.py
  tardis/tests/test_tardis_full_formal_integral.py
  tardis/visualization/tools/tests/test_liv_plot.py
  tardis/visualization/tools/tests/test_sdec_plot.py
Labels: testing :vertical_traffic_light:

#2842 Update docs with regression data
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
  docs/contributing/development/azure_links.inc
  docs/contributing/development/continuous_integration.rst
  docs/contributing/development/index.rst
  docs/contributing/development/links.inc
  docs/contributing/development/running_tests.rst
  docs/contributing/development/update_refdata.rst
  docs/contributing/development/update_regression_data.rst
  docs/index.rst
  docs/multiindex_isotope_decay_data.ipynb
  docs/quickstart.ipynb
Labels: priority - high :fire:, documentation

#2860 Cleanup codestyle workflow
  .github/workflows/codestyle.yml
Labels: CI/CD, codestyle
