Repository tardis-sn/tardis, pull requests merged in 2024-06, with the labels that each got.

#2631 Edit Generation Tests
  .github/workflows/tests.yml
Labels: work in progress 🚧, CI/CD, run-generation-tests

#2573 Bugfix: Added a conditional statement and changed the error type that was being handled in `tardis.io.model_reader.read_uniform_abundances`.
  .mailmap
  tardis/io/model_reader.py
Labels: bugfix :beetle:, build-docs

#2630 Added HDF documentation.
  docs/index.rst
  docs/io/hdf/index.rst
Labels: documentation

#2641 Update Lock Files 2024
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  tardis_env3.yml
Labels: conda, build-docs, benchmarks, run-generation-tests

#2518 Convergence restructure
  tardis/io/configuration/config_reader.py
  tardis/simulation/base.py
  tardis/simulation/convergence.py
  tardis/simulation/tests/test_convergence.py
Labels: restructure, build-docs

#2608 Refactoring of Monte Carlo transport
  benchmarks/benchmark_base.py
  benchmarks/transport_montecarlo_interaction.py
  benchmarks/transport_montecarlo_numba_formal_integral_p.py
  benchmarks/transport_montecarlo_packet.py
  benchmarks/transport_montecarlo_vpacket.py
  docs/physics/spectrum/basic.ipynb
  tardis/gui/widgets.py
  tardis/io/configuration/schemas/montecarlo.yml
  tardis/io/model_reader.py
  tardis/spectrum.py
  tardis/tests/test_spectrum.py
  tardis/transport/montecarlo/base.py
  tardis/transport/montecarlo/estimators/tests/conftest.py
  tardis/transport/montecarlo/formal_integral.py
  tardis/transport/montecarlo/formal_integral_cuda.py
  tardis/transport/montecarlo/montecarlo_main_loop.py
  tardis/transport/montecarlo/montecarlo_transport_state.py
  tardis/transport/montecarlo/nonhomologous_grid.py
  tardis/transport/montecarlo/numba_interface.py
  tardis/transport/montecarlo/r_packet.py
  tardis/transport/montecarlo/r_packet_transport.py
  tardis/transport/montecarlo/single_packet_loop.py
  tardis/transport/montecarlo/tests/conftest.py
  tardis/transport/montecarlo/tests/test_cuda_formal_integral.py
  tardis/transport/montecarlo/tests/test_interaction.py
  tardis/transport/montecarlo/tests/test_macro_atom.py
  tardis/transport/montecarlo/tests/test_montecarlo.py
  tardis/transport/montecarlo/tests/test_numba_formal_integral.py
  tardis/transport/montecarlo/tests/test_packet.py
  tardis/transport/montecarlo/tests/test_single_packet_loop.py
  tardis/transport/montecarlo/tests/test_vpacket.py
  tardis/transport/montecarlo/vpacket.py
Labels: montecarlo :game_die:, restructure, build-docs, benchmarks

#2659 Update Ruff Config
  .ruff.toml
  pyproject.toml
Labels: codestyle

#2609 [Restructure/plasma] Initial Opacities Refactor
  benchmarks/transport_montecarlo_numba_interface.py
  benchmarks/transport_montecarlo_opacities.py
  tardis/energy_input/gamma_packet_loop.py
  tardis/energy_input/gamma_ray_estimators.py
  tardis/energy_input/gamma_ray_interactions.py
  tardis/energy_input/gamma_ray_transport.py
  tardis/energy_input/tests/test_util.py
  tardis/energy_input/util.py
  tardis/opacities/__init__.py
  tardis/opacities/macro_atom/__init__.py
  tardis/opacities/macro_atom/base.py
  tardis/opacities/macro_atom/transition_probabilities.py
  tardis/opacities/macro_atom/util.py
  tardis/opacities/opacities.py
  tardis/opacities/opacity_state.py
  tardis/opacities/tau_sobolev.py
  tardis/plasma/properties/__init__.py
  tardis/plasma/properties/general.py
  tardis/plasma/properties/j_blues.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/properties/radiative_properties.py
  tardis/plasma/standard_plasmas.py
  tardis/radiation_field/base.py
  tardis/transport/montecarlo/formal_integral.py
  tardis/transport/montecarlo/r_packet_transport.py
  tardis/transport/montecarlo/single_packet_loop.py
  tardis/transport/montecarlo/tests/conftest.py
  tardis/transport/montecarlo/tests/test_numba_interface.py
  tardis/transport/montecarlo/tests/test_opacities.py
  tardis/transport/montecarlo/tests/test_packet.py
  tardis/transport/montecarlo/vpacket.py
Labels: restructure, opacity, build-docs

#2665 Fix benchmarks errors
  benchmarks/benchmark_base.py
  benchmarks/transport_montecarlo_interaction.py
  benchmarks/transport_montecarlo_numba_interface.py
  benchmarks/transport_montecarlo_packet.py
  benchmarks/transport_montecarlo_vpacket.py
Labels: build-docs, benchmarks

#2629 Updating github changes command in post release workflow (changelog fix)
  .github/workflows/post-release.yml
  cliff.toml
Labels: priority - high :fire:, CI/CD, infrastructure

#2666 Add Ruff to TARDIS Environment
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  tardis_env3.yml
Labels: codestyle, infrastructure, build-docs, benchmarks, run-generation-tests

#2652 I/O Refactoring
  docs/io/optional/how_to_custom_source.ipynb
  tardis/io/__init__.py
  tardis/io/configuration/schemas/montecarlo_definitions.yml
  tardis/io/model/__init__.py
  tardis/io/model/cmfgen.py
  tardis/io/model/density.py
  tardis/io/model/parse_composition_configuration.py
  tardis/io/model/parse_density_configuration.py
  tardis/io/model/parse_geometry_configuration.py
  tardis/io/model/parse_mass_fraction_configuration.py
  tardis/io/model/parse_packet_source_configuration.py
  tardis/io/model/parse_radiation_field_configuration.py
  tardis/io/model/readers/base.py
  tardis/io/model/readers/cmfgen.py
  tardis/io/model/readers/cmfgen_deprecated.py
  tardis/io/model/readers/csvy.py
  tardis/io/model/readers/generic_readers.py
  tardis/io/model/readers/stella.py
  tardis/io/model/readers/tests/test_ascii_readers.py
  tardis/io/model/readers/tests/test_cmfgen_reader.py
  tardis/io/model/readers/util.py
  tardis/io/model_reader.py
  tardis/io/tests/test_model_reader.py
  tardis/model/base.py
  tardis/model/parse_input.py
  tardis/model/tests/test_csvy_model.py
  tardis/simulation/base.py
  tardis/visualization/widgets/custom_abundance.py
Labels: bugfix :beetle:, io, restructure
