Repository tardis-sn/tardis, pull requests merged in 2024-09, with the labels that each got.

#2814 Move to qgridnext
  .github/workflows/tests.yml
  tardis/visualization/widgets/line_info.py
  tardis/visualization/widgets/util.py
  tardis_env3.yml
Labels: visualization, build-docs

#2808 Migrate to Regression Data Completely
  .github/actions/setup_lfs/action.yml
  .github/workflows/archive/dispatcher.yml
  .github/workflows/build-docs.yml
  .github/workflows/pre-release.yml
  .github/workflows/tests.yml
  asv.conf.json
  docs/io/configuration/components/models/data/config_init_trad.yml
  docs/io/configuration/components/models/data/config_no_init_trad.yml
  docs/resources/code_comparison/plasma_compare/tardis_example.yml
  tardis/conftest.py
  tardis/energy_input/docs/working_gamma_ray_test.ipynb
  tardis/io/model/parse_atom_data.py
  tardis/io/model/readers/tests/data/csvy_test_config.yml
  tardis/io/model/readers/tests/test_arepo_parser.py
  tardis/model/tests/data/branch85_csvy.yml
  tardis/model/tests/data/branch85_old_config.yml
  tardis/model/tests/data/csvy_model_to_test_abundances.yml
  tardis/model/tests/data/exponential_csvy.yml
  tardis/model/tests/data/exponential_old_config.yml
  tardis/model/tests/data/model_full_csvy.yml
  tardis/model/tests/data/model_full_old_config.yml
  tardis/model/tests/data/powerlaw_csvy.yml
  tardis/model/tests/data/powerlaw_old_config.yml
  tardis/model/tests/data/radiative_csvy.yml
  tardis/model/tests/data/radiative_old_config.yml
  tardis/model/tests/data/uniform_csvy.yml
  tardis/model/tests/data/uniform_old_config.yml
  tardis/plasma/tests/data/config_init_trad.yml
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/spectrum/tests/__init__.py
  tardis/tests/fixtures/atom_data.py
Labels: build-docs

#2826 Ruff Autofixes (tardis/analysis)
  tardis/analysis/opacities.py
  tardis/grid/__init__.py
  tardis/grid/base.py
  tardis/grid/tests/test_grid.py
  tardis/radiation_field/base.py
  tardis/util/base.py
Labels: codestyle

#2827 Ruff `tardis/io`
  tardis/io/atom_data/__init__.py
  tardis/io/atom_data/base.py
  tardis/io/atom_data/util.py
  tardis/io/configuration/config_internal.py
  tardis/io/configuration/config_reader.py
  tardis/io/configuration/config_validator.py
  tardis/io/configuration/tests/test_config_reader.py
  tardis/io/configuration/tests/test_configuration_namespace.py
  tardis/io/logger/__init__.py
  tardis/io/logger/colored_logger.py
  tardis/io/logger/logger.py
  tardis/io/logger/montecarlo_tracking.py
  tardis/io/logger/tests/test_logging.py
  tardis/io/model/__init__.py
  tardis/io/model/readers/arepo.py
  tardis/io/model/readers/artis.py
  tardis/io/model/readers/base.py
  tardis/io/model/readers/blondin_toymodel.py
  tardis/io/model/readers/cmfgen.py
  tardis/io/model/readers/cmfgen_deprecated.py
  tardis/io/model/readers/csvy.py
  tardis/io/model/readers/generic_readers.py
  tardis/io/model/readers/stella.py
  tardis/io/model/readers/tests/test_arepo_parser.py
  tardis/io/model/readers/tests/test_ascii_readers.py
  tardis/io/model/readers/tests/test_cmfgen_reader.py
  tardis/io/model/readers/tests/test_csvy_reader.py
  tardis/io/model/readers/tests/test_stella_reader.py
  tardis/io/tests/test_HDFWriter.py
  tardis/io/tests/test_atomic.py
  tardis/io/tests/test_decay.py
  tardis/io/tests/test_model_reader.py
  tardis/io/util.py
Labels: codestyle

#2828 Ruff `tardis/model`
  tardis/model/__init__.py
  tardis/model/base.py
  tardis/model/geometry/radial1d.py
  tardis/model/geometry/tests/test_radial1d.py
  tardis/model/matter/decay.py
  tardis/model/tests/test_base.py
  tardis/model/tests/test_csvy_model.py
  tardis/model/tests/test_density.py
Labels: codestyle

#2832 Failing Docs Fix
  docs/contributing/tools/benchmark.ipynb
  docs/contributing/tools/profiling/profiling_example.ipynb
  docs/contributing/tools/profiling/tardis_profiling_threads.ipynb
  docs/io/grid/how_to_TardisGridTutorial.ipynb
  docs/io/optional/tutorial_callback_example.ipynb
  docs/io/optional/tutorial_logging_configuration.ipynb
  docs/io/output/how_to_physical_quantities.ipynb
  docs/io/output/how_to_plasma_graph.ipynb
  docs/io/output/how_to_rpacket_tracking.ipynb
  docs/io/output/how_to_to_hdf.ipynb
  docs/io/visualization/how_to_generating_widgets.ipynb
  docs/io/visualization/how_to_liv_plot.ipynb
  docs/io/visualization/how_to_sdec_plot.ipynb
  docs/io/visualization/tutorial_convergence_plot.ipynb
  docs/io/visualization/tutorial_montecarlo_packet_visualization.ipynb
  docs/multiindex_isotope_decay_data.ipynb
  docs/physics/nlte/nlte_rates.ipynb
  docs/physics/setup/model.ipynb
  docs/physics/setup/setup_example.ipynb
  docs/physics/spectrum/basic.ipynb
  docs/physics/update_and_conv/update_and_conv.ipynb
  docs/quickstart.ipynb
  tardis/io/atom_data/util.py
Labels: build-docs

#2830 Fix for #2820
  .github/workflows/tests.yml
Labels: CI/CD, build-docs

#2823 Handle Test warnings
  tardis/io/configuration/tests/data/tardis_configv1_verysimple.yml
  tardis/io/model/readers/cmfgen.py
  tardis/io/util.py
  tardis/plasma/properties/helium_nlte.py
  tardis/plasma/properties/ion_population.py
  tardis/plasma/properties/level_population.py
  tardis/plasma/properties/partition_function.py
  tardis/spectrum/tests/test_spectrum.py
  tardis/visualization/tools/convergence_plot.py
  tardis/visualization/tools/liv_plot.py
  tardis/visualization/tools/sdec_plot.py
Labels: bugfix :beetle:

#2831 Failing benchmarks fix
  .github/workflows/benchmarks.yml
Labels: benchmarks

#2816 Release Modifications
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: CI/CD, infrastructure

#2834 Fixes qgridnext import error in tests
  tardis/visualization/widgets/util.py
Labels: bugfix :beetle:, testing :vertical_traffic_light:, build-docs
