Repository tardis-sn/tardis, pull requests merged in 2024-08, with the labels that each got.

#2761 Donot run docs, benchmarks and stardis tests on draft PRs.
  .github/workflows/benchmarks.yml
  .github/workflows/build-docs.yml
  .github/workflows/stardis-tests.yml
Labels: infrastructure

#2771 Add Extend Array Function
  tardis/transport/montecarlo/packet_trackers.py
  tardis/transport/montecarlo/tests/test_rpacket_tracker.py
Labels: restructure

#2762 Fix ruff comments issue
  .github/workflows/codestyle.yml
Labels: codestyle

#2749 Cache benchmark functions
  .github/workflows/benchmarks.yml
  benchmarks/benchmark_base.py
  benchmarks/opacities_opacity.py
  benchmarks/opacities_opacity_state.py
  benchmarks/run_tardis.py
  benchmarks/spectrum_formal_integral.py
  benchmarks/transport_geometry_calculate_distances.py
  benchmarks/transport_montecarlo_estimators_radfield_estimator_calcs.py
  benchmarks/transport_montecarlo_interaction.py
  benchmarks/transport_montecarlo_main_loop.py
  benchmarks/transport_montecarlo_packet_trackers.py
  benchmarks/transport_montecarlo_single_packet_loop.py
  benchmarks/transport_montecarlo_vpacket.py
  benchmarks/util/__init__.py
  benchmarks/util/base.py
  benchmarks/util/nlte.py
Labels: benchmarks

#2773 Opacity state restructure
  tardis/opacities/continuum/continuum_state.py
  tardis/opacities/macro_atom/macroatom_state.py
  tardis/opacities/opacity_solver.py
  tardis/opacities/opacity_state.py
  tardis/opacities/tests/conftest.py
  tardis/opacities/tests/test_opacity_solver.py
  tardis/opacities/tests/test_opacity_state_numba.py
  tardis/transport/montecarlo/base.py
Labels: restructure, opacity

#2778 Ruff Fix 2
  .github/workflows/codestyle.yml
Labels: bugfix :beetle:

#2759 Minor refactor of the spectrum solver
  benchmarks/spectrum_formal_integral.py
  docs/physics/update_and_conv/update_and_conv.ipynb
  tardis/simulation/base.py
  tardis/spectrum/base.py
  tardis/spectrum/luminosity.py
  tardis/spectrum/tests/test_luminosity.py
Labels: build-docs, benchmarks

#2782 Change parameters in benchmarks
  benchmarks/opacities_opacity.py
  benchmarks/transport_montecarlo_packet_trackers.py
Labels: benchmarks

#2748 [restructure/plasma] Cleanup plasma assembly
  docs/physics/plasma/construction_simple_plasma.ipynb
  tardis/io/configuration/tests/test_config_reader.py
  tardis/model/base.py
  tardis/opacities/opacity_solver.py
  tardis/plasma/assembly/__init__.py
  tardis/plasma/assembly/base.py
  tardis/plasma/assembly/legacy_assembly.py
  tardis/plasma/base.py
  tardis/plasma/properties/general.py
  tardis/plasma/properties/ion_population.py
  tardis/plasma/properties/nlte.py
  tardis/plasma/properties/property_collections.py
  tardis/plasma/properties/radiative_properties.py
  tardis/plasma/tests/test_nlte_solver.py
  tardis/plasma/tests/test_tardis_model_density_config.py
  tardis/simulation/base.py
  tardis/transport/montecarlo/estimators/tests/test_continuum_property_solver.py
  tardis/visualization/widgets/shell_info.py
  tardis/visualization/widgets/tests/test_shell_info.py
Labels: build-docs, benchmarks

#2786 Macroatom restructure
  tardis/opacities/macro_atom/base.py
  tardis/opacities/macro_atom/macroatom_solver.py
  tardis/opacities/opacity_solver.py
  tardis/opacities/opacity_state.py
  tardis/opacities/tests/test_opacity_solver.py
  tardis/opacities/tests/test_opacity_state_numba.py
  tardis/simulation/base.py
  tardis/transport/montecarlo/base.py
Labels: restructure, opacity

#2784 Add Packet Wavelength filter to LIV Plot
  docs/io/visualization/how_to_liv_plot.ipynb
  tardis/visualization/tools/liv_plot.py
Labels: visualization

#2801 Fix file formats
  .github/workflows/codestyle.yml
  tardis/opacities/macro_atom/macroatom_solver.py
  tardis/opacities/opacity_solver.py
Labels: codestyle

#2799 Remove syrupy section from docs
  docs/contributing/development/running_tests.rst
Labels: documentation

#2785 Convert SDEC tests to Regression Data
  tardis/visualization/tools/tests/test_sdec_plot.py
Labels: testing :vertical_traffic_light:

#2798 Remove deprecated setup.py
  asv.conf.json
  docs/Makefile
  docs/conf.py
  docs/contributing/development/documentation_guidelines.rst
  docs/contributing/development/git_workflow.rst
  docs/contributing/development/running_tests.rst
  docs/installation.rst
  pyproject.toml
  setup.py
  tardis/tests/integration_tests/runner.py
Labels: infrastructure

#2794 Update research papers notebook and update the docs
  .github/workflows/tardis-research-papers.yml
  docs/resources/research_done_using_TARDIS/ads.ipynb
Labels: documentation

#2783 Simple Atom data refactor
  tardis/io/atom_data/base.py
  tardis/io/atom_data/collision_data.py
  tardis/io/atom_data/macro_atom_data.py
  tardis/io/atom_data/nlte_data.py
  tardis/plasma/nlte/__init__.py
Labels: atomic, restructure

#2723 LIV Plot Tests
  tardis/visualization/tools/liv_plot.py
  tardis/visualization/tools/tests/test_liv_plot.py
Labels: testing :vertical_traffic_light:, visualization

#2805 TARDIS Full Formal Integral Regression Tests
  tardis/conftest.py
  tardis/gui/tests/test_gui.py
  tardis/spectrum/base.py
  tardis/tests/test_tardis_full_formal_integral.py
Labels: testing :vertical_traffic_light:

#2806 Add molecular data exposure to tardis atom data
  tardis/io/atom_data/base.py
Labels: atomic

#2795 Doc changes for RPacketTracker
  docs/io/output/how_to_rpacket_tracking.ipynb
Labels: documentation
