Repository tardis-sn/tardis, pull requests merged in 2024-03, with the labels that each got.

#2522 prevent float overflow when calculating He I population
  tardis/model/parse_input.py
Labels: bugfix :beetle:, build-docs

#2533 Fix broken URL in generating_widgets.ipynb
  .mailmap
  docs/io/visualization/generating_widgets.ipynb
Labels: GSoC :sun_with_face:, build-docs

#2541 Fix units for virtual packet properties in MonteCarloTransportState
  tardis/montecarlo/montecarlo_transport_state.py
Labels: GSoC :sun_with_face:, build-docs

#2529 PR to separate main gamma ray loop
  docs/working_gamma_ray_test.ipynb
  tardis/energy_input/GXPacket.py
  tardis/energy_input/gamma_packet_loop.py
  tardis/energy_input/gamma_ray_transport.py
  tardis/energy_input/main_gamma_ray_loop.py
  tardis/model/base.py
  tardis/model/matter/composition.py
  tardis/model/parse_input.py
Labels: nebular, build-docs

#2253 Fix for widgets displaying code in commandline
  tardis/simulation/base.py
  tardis/tests/test_util.py
  tardis/visualization/tools/tests/test_convergence_plot.py
  tardis/visualization/widgets/custom_abundance.py
  tardis/visualization/widgets/line_info.py
  tardis/visualization/widgets/shell_info.py
  tardis/visualization/widgets/tests/test_custom_abundance.py
  tardis/visualization/widgets/tests/test_line_info.py
  tardis/visualization/widgets/tests/test_shell_info.py
Labels: bugfix :beetle:, visualization

#2553 Fix Cache IDs in Tests Workflow
  .github/workflows/tests.yml
Labels: testing :vertical_traffic_light:, infrastructure

#2535 Path.replace bug
  .mailmap
  tardis/io/atom_data/base.py
  tardis/io/atom_data/util.py
  tardis/simulation/base.py
Labels: GSoC :sun_with_face:, build-docs

#2554 Remove Azure Compare Refdata Pipeline
  .azure-pipelines/compare-refdata.yml
  .azure-pipelines/templates/default.yml
  .github/workflows/pre-release.yml
Labels: infrastructure
