Repository tardis-sn/tardis, pull requests merged in 2025-05, with the labels that each got.

#3029 add convergence notebook to analysing tardis outputs section
  docs/analyzing_tardis/analysing_convergence_plot.ipynb
  docs/index.rst
  tardis/simulation/base.py
  tardis/visualization/plot_util.py
  tardis/visualization/tools/convergence_plot.py
  tardis/visualization/tools/tests/test_convergence_plot.py
  tardis/visualization/widgets/custom_abundance.py
Labels: visualization

#3067 Cleanup rpacket plotter class
  tardis/visualization/tools/rpacket_plot.py
  tardis/visualization/tools/tests/test_rpacket_plot.py
Labels: restructure

#2998 Created a workflow for TARDIS High energy
  docs/workflows/workflow_notebook.ipynb
  tardis/workflows/tardis_he_workflow.py
Labels: gamma-ray

#3075 Build docs issues fixes
  tardis/io/model/parse_composition_configuration.py
  tardis/io/model/parse_density_configuration.py
Labels: build-docs

#3069 Cleanup sdec and liv plotter classes
  tardis/visualization/plot_util.py
  tardis/visualization/tests/test_plot_util.py
  tardis/visualization/tools/liv_plot.py
  tardis/visualization/tools/sdec_plot.py
  tardis/visualization/tools/tests/test_sdec_plot.py
Labels: restructure, build-docs
