Repository tardis-sn/tardis, pull requests merged in 2025-03, with the labels that each got.

#2993 Regression data comparison workflow
  .github/workflows/compare-regdata.yml
Labels: CI/CD, run-regression-comparison

#2999 Trigger LFS-cache generation from regression data repository
  .github/workflows/lfs-cache.yml
Labels: CI/CD

#2982 [Docs] : updated the pytest arg from --regression-data to --tardis-regression-data
  .mailmap
  docs/contributing/development/update_regression_data.rst
Labels: documentation

#2984 Fix init bug for: line_interaction_type=scatter
  .mailmap
  tardis/simulation/base.py
Labels: bugfix :beetle:

#3004 Fix post release workflow by pinning python version to 3.12
  .github/workflows/post-release.yml
Labels: CI/CD

#3001 Document `LFS-cache` workflow and the `setup-lfs` action
  .github/workflows/compare-regdata.yml
  docs/contributing/development/continuous_integration.rst
Labels: documentation

#2981 v_inner_solver store plasma state fxn
  tardis/io/configuration/schemas/montecarlo_definitions.yml
  tardis/workflows/v_inner_solver.py
Labels: plasma

#3002 Flatten macroatom
  tardis/opacities/macro_atom/base.py
  tardis/opacities/macro_atom/macroatom_solver.py
Labels: restructure, opacity

#3030 BugFix: Utility workflow and Clean Docs workflow
  .github/workflows/clean-docs.yml
  .github/workflows/util.yml
Labels: CI/CD

#3013 Upgrade dependencies by resolving TARDIS environment
  .ruff.toml
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  conda-osx-arm64.lock
  docs/io/output/how_to_plasma_graph.ipynb
  tardis/base.py
  tardis/conftest.py
  tardis/transport/montecarlo/montecarlo_main_loop.py
  tardis/visualization/tools/convergence_plot.py
  tardis/visualization/tools/tests/test_convergence_plot.py
  tardis_env3.yml
Labels: build-docs, run-regression-comparison
