Repository tardis-sn/tardis, pull requests merged in 2025-06, with the labels that each got.

#3112 Correct atomic data path and checksum
  tardis/data/atomic_data_repo.yml
Labels: bugfix :beetle:

#3085 Updated sdec plot notebook
  docs/analyzing_tardis/spectrum/sdec_notebook.ipynb
Labels: run-regression-comparison

#3118 Complete job names for status checks
  .github/workflows/compare-regdata.yml
  .github/workflows/tests.yml
Labels: priority - high :fire:

#2974 Refactor isotope mass fraction handling and configuration
  tardis/energy_input/tests/test_gamma_ray_channel.py
  tardis/io/configuration/schemas/model_definitions.yml
  tardis/io/model/parse_composition_configuration.py
  tardis/io/model/parse_mass_fraction_configuration.py
  tardis/model/matter/composition.py
  tardis/model/tests/test_base.py
  tardis/model/tests/test_csvy_model.py
  tardis/plasma/tests/test_tardis_model_density_config.py
Labels: gamma-ray

#3100 Use lineid plot to make spectral line markers
  .mailmap
  .orcid.csv
  docs/analyzing_tardis/visualization/how_to_sdec_plot.ipynb
  tardis/visualization/tools/lineid_plotter.py
  tardis/visualization/tools/tests/test_lineid_plotter.py
Labels: documentation, feature

#3098 Logging in vinner solver and catching nans
  tardis/workflows/v_inner_solver.py
Labels: logging

#3124 Use lock files from tardisbase
  .github/actions/setup_env/action.yml
  .github/workflows/archive/update-refdata.yml
  .github/workflows/build-docs.yml
  .github/workflows/codespell.yml
  .github/workflows/codestyle.yml
  .github/workflows/compare-regdata.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-arm64.lock
  docs/installation.rst
  tardis_env3.yml
Labels: build-docs

#3132 Fix `build-docs`
  .github/workflows/build-docs.yml
  docs/Makefile
  docs/conf.py
  docs/physics/setup/model.ipynb
  tardis/workflows/v_inner_solver.py
Labels: build-docs

#3101 Regression data from `tardisbase`
  .github/workflows/tests.yml
  pyproject.toml
  tardis/conftest.py
  tardis/plasma/tests/test_complete_plasmas.py
  tardis/spectrum/tests/test_spectrum_solver.py
  tardis/tests/fixtures/regression_data.py
  tardis/tests/test_tardis_full.py
  tardis/tests/test_tardis_full_formal_integral.py
  tardis/visualization/tests/test_plot_util.py
  tardis/visualization/tools/tests/test_liv_plot.py
  tardis/visualization/tools/tests/test_sdec_plot.py
Labels: CI/CD

#3148 Update config validator to use Draft 7 and improve schema registry handling
  tardis/io/configuration/config_validator.py
Labels: build-docs

#3157 Tests/validator
  tardis/io/configuration/tests/test_config_validator.py
Labels: testing :vertical_traffic_light:

#3116 Macroatom restructure
  .orcid.csv
  tardis/opacities/macro_atom/macroatom_solver.py
  tardis/opacities/macro_atom/macroatom_state.py
  tardis/opacities/macro_atom/macroatom_transitions.py
  tardis/opacities/tests/test_opacity_solver.py
  tardis/opacities/tests/test_opacity_state_numba.py
  tardis/simulation/base.py
  tardis/workflows/simple_tardis_workflow.py
Labels: restructure

#3094 Update workflow to use comparison tools from tardisbase repository
  .github/workflows/compare-regdata.yml
  .mailmap
Labels: run-regression-comparison

#3032 Remove test from __init__.py
  tardis/__init__.py
Labels: bugfix :beetle:, build-docs

#3146 use pytest.importorskip on optional visualization dependencies
  tardis/visualization/tools/tests/test_lineid_plotter.py
  tardis/visualization/widgets/tests/test_line_info.py
  tardis/visualization/widgets/tests/test_shell_info.py
Labels: conda
