Repository tardis-sn/tardis, pull requests merged in 2025-08, with the labels that each got.

#3177 Refactor `make_source_function` into solver
  benchmarks/spectrum_formal_integral.py
  tardis/spectrum/formal_integral/base.py
  tardis/spectrum/formal_integral/formal_integral.py
  tardis/spectrum/formal_integral/formal_integral_cuda.py
  tardis/spectrum/formal_integral/formal_integral_numba.py
  tardis/spectrum/formal_integral/source_function.py
  tardis/spectrum/formal_integral/tests/test_cuda_formal_integral.py
  tardis/spectrum/formal_integral/tests/test_formal_integral.py
  tardis/spectrum/formal_integral/tests/test_numba_formal_integral.py
  tardis/spectrum/formal_integral/tests/test_source_function.py
  tardis/tests/test_tardis_full_formal_integral.py
Labels: build-docs

#3221 Revert "Restructure/transport solver v1"
  tardis/simulation/base.py
  tardis/transport/montecarlo/base.py
  tardis/workflows/simple_tardis_workflow.py
Labels: bugfix :beetle:, build-docs

#3194 Updated readme
  README.rst
  docs/tardis.bib
Labels: documentation

#3186 Add Dependabot for GitHub Actions Updates
  .github/dependabot.yml
Labels: CI/CD

#3200 3131: solved Docs Template contains fork reference
  docs/_templates/layout.html
Labels: documentation

#3249 Fix default `interpolate_shells` in Formal Integral
  tardis/spectrum/formal_integral/formal_integral_solver.py
Labels: bugfix :beetle:, run-regression-comparison

#3227 Clean FormalIntegralSolver
  benchmarks/spectrum_formal_integral.py
  tardis/simulation/base.py
  tardis/spectrum/base.py
  tardis/spectrum/formal_integral/formal_integral_solver.py
  tardis/spectrum/formal_integral/source_function.py
  tardis/spectrum/formal_integral/tests/test_cuda_formal_integral.py
  tardis/spectrum/formal_integral/tests/test_source_function.py
  tardis/workflows/simple_tardis_workflow.py
Labels: restructure

#3257 Revise dependencies in README
  README.rst
Labels: documentation
