Repository tardis-sn/tardis, pull requests merged in 2025-01, with the labels that each got.

#2923 Moves non-physical input check outsode I/O module
  .mailmap
  tardis/io/model/parse_radiation_field_configuration.py
  tardis/radiation_field/validate_radiation_field.py
Labels: restructure

#2925 give tag in git cliff command
  .github/workflows/release.yml
Labels: CI/CD

#2908 Ignore ipynb files in codespell
  pyproject.toml
Labels: CI/CD

#2907 Add missing init.py file in opacitites module
  tardis/opacities/tests/__init__.py
Labels: testing :vertical_traffic_light:

#2946 Fixes indentation for tracking key to be nested under montecarlo key in YAML
  docs/io/output/how_to_rpacket_tracking.ipynb
Labels: codestyle

#2800 V inner formal integral
  docs/physics/setup/model.ipynb
  docs/workflows/v_inner_solver_workflow.ipynb
  tardis/io/configuration/config_reader.py
  tardis/io/configuration/schemas/montecarlo_definitions.yml
  tardis/io/model/parse_geometry_configuration.py
  tardis/model/base.py
  tardis/spectrum/formal_integral.py
  tardis/workflows/simple_tardis_workflow.py
  tardis/workflows/util.py
  tardis/workflows/v_inner_solver.py
Labels: formal integral, restructure, in review

#2938 Fixes spelling errors in the codebase
  docs/contributing/development/benchmarks.rst
  tardis/opacities/continuum/continuum_state.py
  tardis/opacities/macro_atom/macroatom_solver.py
  tardis/opacities/macro_atom/macroatom_state.py
  tardis/opacities/opacity_solver.py
  tardis/opacities/opacity_state.py
Labels: codestyle, GSoC :sun_with_face:

#2897 Ionization rates
  docs/physics/plasma/equilibrium/tardis_solver_cmfgen.ipynb
  tardis/plasma/electron_energy_distribution/base.py
  tardis/plasma/equilibrium/rates/__init__.py
  tardis/plasma/equilibrium/rates/collisional_ionization_rates.py
  tardis/plasma/equilibrium/rates/collisional_ionization_strengths.py
  tardis/plasma/equilibrium/rates/photoionization_rates.py
  tardis/plasma/equilibrium/rates/photoionization_strengths.py
Labels: plasma, restructure

#2954 LFS Fixes
  .github/actions/setup_env/action.yml
  .github/actions/setup_lfs/action.yml
  .github/workflows/benchmarks.yml
  .github/workflows/build-docs.yml
  .github/workflows/lfs-cache.yml
  .github/workflows/tests.yml
  docs/contributing/development/continuous_integration.rst
  docs/contributing/development/running_tests.rst
Labels: documentation, CI/CD
