Repository tardis-sn/tardis, pull requests merged in 2025-02, with the labels that each got.

#2965 Disallow Merge Refs from Creating Cache
  .github/workflows/lfs-cache.yml
Labels: CI/CD

#2963 updated converged status to self.converged throughout workflow
  tardis/workflows/simple_tardis_workflow.py
  tardis/workflows/standard_tardis_workflow.py
  tardis/workflows/v_inner_solver.py
Labels: bugfix :beetle:

#2966 Fix LFS sparse checkout
  .github/actions/setup_lfs/action.yml
  .github/workflows/lfs-cache.yml
Labels: build-docs

#2956 Fixes the codestyle for Invalid Class Names
  docs/io/grid/how_to_TardisGridTutorial.ipynb
  tardis/analysis/opacities.py
  tardis/grid/base.py
  tardis/grid/tests/test_grid.py
Labels: codestyle, GSoC :sun_with_face:

#2951 Ensures consistency across codebase to ensure consistent codestyle
  tardis/io/model/readers/tests/test_arepo_parser.py
  tardis/plasma/tests/test_tardis_model_density_config.py
  tardis/transport/montecarlo/tests/conftest.py
  tardis/transport/montecarlo/tests/test_rpacket_last_interaction_tracker.py
  tardis/transport/montecarlo/tests/test_rpacket_tracker.py
  tardis/visualization/tools/tests/test_convergence_plot.py
Labels: codestyle, GSoC :sun_with_face:

#2975 Fail LFS pull if label not present
  .github/workflows/benchmarks.yml
  .github/workflows/build-docs.yml
  .github/workflows/lfs-cache.yml
  .github/workflows/tests.yml
Labels: priority - high :fire:, CI/CD

#2967 Move visualization section to analysing tardis output
  docs/analysing_tardis_outputs/visualization/demo_observed_spectrum.dat
  docs/analysing_tardis_outputs/visualization/how_to_abundance_widget.ipynb
  docs/analysing_tardis_outputs/visualization/how_to_generating_widgets.ipynb
  docs/analysing_tardis_outputs/visualization/how_to_liv_plot.ipynb
  docs/analysing_tardis_outputs/visualization/how_to_sdec_plot.ipynb
  docs/analysing_tardis_outputs/visualization/index.rst
  docs/analysing_tardis_outputs/visualization/tardis_example.yml
  docs/analysing_tardis_outputs/visualization/tutorial_convergence_plot.ipynb
  docs/analysing_tardis_outputs/visualization/tutorial_montecarlo_packet_visualization.ipynb
  docs/analysing_tardis_outputs/visualization/using_widgets.rst
  docs/index.rst
Labels: documentation

#2962 Updated packet_source to fix bug with BlackBodySimpleSource.create_pa…
  tardis/transport/montecarlo/packet_source.py
Labels: relativity, bugfix :beetle:

#2935 Numpy v2 Upgrade PR 2
  .github/actions/setup_lfs/action.yml
  .github/workflows/lfs-cache.yml
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-arm64.lock
  tardis/io/atom_data/base.py
  tardis/io/model/readers/generic_readers.py
  tardis/transport/montecarlo/tests/test_rpacket_tracker.py
Labels: build-docs, benchmarks, git-lfs-pull

#2793 Gamma ray spectra dep
  .mailmap
  tardis/energy_input/GXPacket.py
  tardis/energy_input/gamma_packet_loop.py
  tardis/energy_input/gamma_ray_channel.py
  tardis/energy_input/gamma_ray_grid.py
  tardis/energy_input/gamma_ray_interactions.py
  tardis/energy_input/gamma_ray_packet_source.py
  tardis/energy_input/main_gamma_ray_loop.py
  tardis/energy_input/samplers.py
  tardis/energy_input/tests/conftest.py
  tardis/energy_input/tests/test_gamma_ray_channel.py
  tardis/energy_input/tests/test_gamma_ray_grid.py
  tardis/energy_input/tests/test_gamma_ray_interactions.py
  tardis/energy_input/util.py
Labels: gamma-ray, in review
