Repository tardis-sn/tardis, pull requests merged in 2025-04, with the labels that each got.

#2973 Io artis reader
  docs/io/model/data/artis_abundances.dat
  docs/io/model/data/artis_model.dat
  docs/io/model/how_to_read_artis_model.ipynb
  docs/io/model/index.rst
  tardis/io/model/readers/__init__.py
  tardis/io/model/readers/artis.py
  tardis/io/model/readers/tests/test_artis_readers.py
  tardis/io/model/readers/tests/test_ascii_readers.py
  tardis/io/tests/test_model_reader.py
Labels: io

#3012 Changed name from TARDIS-gamma to TARDIS-HE to match the paper.
  docs/physics/tardisgamma/index.rst
Labels: documentation

#2983 v_inner convergence plots in docs
  docs/workflows/v_inner_solver_workflow.ipynb
  tardis/workflows/v_inner_solver.py
Labels: documentation

#2876 Gammaray opacity documentation
  docs/index.rst
  docs/physics/tardisgamma/images/all_coeffs.png
  docs/physics/tardisgamma/images/coeff_fractions.png
  docs/physics/tardisgamma/images/compton_diagram.png
  docs/physics/tardisgamma/images/compton_scattering_coefficient.png
  docs/physics/tardisgamma/images/pair_production_coefficient.png
  docs/physics/tardisgamma/images/pair_production_diagram.jpg
  docs/physics/tardisgamma/images/photoabsorption_coefficient.png
  docs/physics/tardisgamma/index.rst
  docs/physics/tardisgamma/opacities.ipynb
  docs/tardis.bib
Labels: documentation, gamma-ray

#2872 Logger Widget Panel
  asv.conf.json
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-arm64.lock
  docs/Makefile
  docs/conf.py
  tardis/base.py
  tardis/io/logger/__init__.py
  tardis/io/logger/colored_logger.py
  tardis/io/logger/logger.py
  tardis/simulation/base.py
  tardis/visualization/tools/convergence_plot.py
  tardis_env3.yml
Labels: documentation, run-regression-comparison

#2977 Fixture fixes
  tardis/conftest.py
  tardis/spectrum/tests/test_spectrum_solver.py
Labels: testing :vertical_traffic_light:, run-regression-comparison

#3043 Add workflows to documentation
  docs/conf.py
  docs/index.rst
  docs/workflows/simple_workflow.ipynb
  docs/workflows/standard_workflow.ipynb
  docs/workflows/v_inner_solver_workflow.ipynb
Labels: documentation

#3055 Progress Bar Fixes
  benchmarks/transport_montecarlo_main_loop.py
  tardis/conftest.py
  tardis/transport/montecarlo/montecarlo_main_loop.py
  tardis/workflows/standard_tardis_workflow.py
Labels: build-docs

#2846 Ruff `tardis/visualization`
  tardis/conftest.py
  tardis/visualization/__init__.py
  tardis/visualization/plot_util.py
  tardis/visualization/tools/convergence_plot.py
  tardis/visualization/tools/liv_plot.py
  tardis/visualization/tools/rpacket_plot.py
  tardis/visualization/tools/tests/test_convergence_plot.py
  tardis/visualization/tools/tests/test_liv_plot.py
  tardis/visualization/tools/tests/test_rpacket_plot.py
  tardis/visualization/tools/tests/test_sdec_plot.py
  tardis/visualization/widgets/custom_abundance.py
  tardis/visualization/widgets/grotrian.py
  tardis/visualization/widgets/line_info.py
  tardis/visualization/widgets/shell_info.py
  tardis/visualization/widgets/tests/test_custom_abundance.py
  tardis/visualization/widgets/tests/test_line_info.py
  tardis/visualization/widgets/tests/test_shell_info.py
Labels: codestyle, build-docs, run-regression-comparison

#3058 Docs build and logger widget fixes
  .github/actions/setup_env/action.yml
  .github/workflows/benchmarks.yml
  .github/workflows/codestyle.yml
  .github/workflows/compare-regdata.yml
  .github/workflows/stardis-tests.yml
  .github/workflows/tardis-research-papers.yml
  .ruff.toml
  docs/conf.py
  docs/io/output/how_to_to_hdf.ipynb
  tardis/base.py
  tardis/io/logger/colored_logger.py
  tardis/io/logger/logger.py
  tardis/visualization/tools/convergence_plot.py
Labels: build-docs
